
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AppointmentItem` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AppointmentItem
 * 
 */
export type AppointmentItemModel = runtime.Types.Result.DefaultSelection<Prisma.$AppointmentItemPayload>

export type AggregateAppointmentItem = {
  _count: AppointmentItemCountAggregateOutputType | null
  _avg: AppointmentItemAvgAggregateOutputType | null
  _sum: AppointmentItemSumAggregateOutputType | null
  _min: AppointmentItemMinAggregateOutputType | null
  _max: AppointmentItemMaxAggregateOutputType | null
}

export type AppointmentItemAvgAggregateOutputType = {
  durationMin: number | null
  priceCents: number | null
}

export type AppointmentItemSumAggregateOutputType = {
  durationMin: number | null
  priceCents: number | null
}

export type AppointmentItemMinAggregateOutputType = {
  id: string | null
  appointmentId: string | null
  serviceId: string | null
  nameFrSnapshot: string | null
  nameHeSnapshot: string | null
  durationMin: number | null
  priceCents: number | null
}

export type AppointmentItemMaxAggregateOutputType = {
  id: string | null
  appointmentId: string | null
  serviceId: string | null
  nameFrSnapshot: string | null
  nameHeSnapshot: string | null
  durationMin: number | null
  priceCents: number | null
}

export type AppointmentItemCountAggregateOutputType = {
  id: number
  appointmentId: number
  serviceId: number
  nameFrSnapshot: number
  nameHeSnapshot: number
  durationMin: number
  priceCents: number
  _all: number
}


export type AppointmentItemAvgAggregateInputType = {
  durationMin?: true
  priceCents?: true
}

export type AppointmentItemSumAggregateInputType = {
  durationMin?: true
  priceCents?: true
}

export type AppointmentItemMinAggregateInputType = {
  id?: true
  appointmentId?: true
  serviceId?: true
  nameFrSnapshot?: true
  nameHeSnapshot?: true
  durationMin?: true
  priceCents?: true
}

export type AppointmentItemMaxAggregateInputType = {
  id?: true
  appointmentId?: true
  serviceId?: true
  nameFrSnapshot?: true
  nameHeSnapshot?: true
  durationMin?: true
  priceCents?: true
}

export type AppointmentItemCountAggregateInputType = {
  id?: true
  appointmentId?: true
  serviceId?: true
  nameFrSnapshot?: true
  nameHeSnapshot?: true
  durationMin?: true
  priceCents?: true
  _all?: true
}

export type AppointmentItemAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppointmentItem to aggregate.
   */
  where?: Prisma.AppointmentItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppointmentItems to fetch.
   */
  orderBy?: Prisma.AppointmentItemOrderByWithRelationInput | Prisma.AppointmentItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AppointmentItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppointmentItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppointmentItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AppointmentItems
  **/
  _count?: true | AppointmentItemCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AppointmentItemAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AppointmentItemSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AppointmentItemMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AppointmentItemMaxAggregateInputType
}

export type GetAppointmentItemAggregateType<T extends AppointmentItemAggregateArgs> = {
      [P in keyof T & keyof AggregateAppointmentItem]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAppointmentItem[P]>
    : Prisma.GetScalarType<T[P], AggregateAppointmentItem[P]>
}




export type AppointmentItemGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppointmentItemWhereInput
  orderBy?: Prisma.AppointmentItemOrderByWithAggregationInput | Prisma.AppointmentItemOrderByWithAggregationInput[]
  by: Prisma.AppointmentItemScalarFieldEnum[] | Prisma.AppointmentItemScalarFieldEnum
  having?: Prisma.AppointmentItemScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AppointmentItemCountAggregateInputType | true
  _avg?: AppointmentItemAvgAggregateInputType
  _sum?: AppointmentItemSumAggregateInputType
  _min?: AppointmentItemMinAggregateInputType
  _max?: AppointmentItemMaxAggregateInputType
}

export type AppointmentItemGroupByOutputType = {
  id: string
  appointmentId: string
  serviceId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  durationMin: number
  priceCents: number
  _count: AppointmentItemCountAggregateOutputType | null
  _avg: AppointmentItemAvgAggregateOutputType | null
  _sum: AppointmentItemSumAggregateOutputType | null
  _min: AppointmentItemMinAggregateOutputType | null
  _max: AppointmentItemMaxAggregateOutputType | null
}

export type GetAppointmentItemGroupByPayload<T extends AppointmentItemGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AppointmentItemGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AppointmentItemGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AppointmentItemGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AppointmentItemGroupByOutputType[P]>
      }
    >
  >



export type AppointmentItemWhereInput = {
  AND?: Prisma.AppointmentItemWhereInput | Prisma.AppointmentItemWhereInput[]
  OR?: Prisma.AppointmentItemWhereInput[]
  NOT?: Prisma.AppointmentItemWhereInput | Prisma.AppointmentItemWhereInput[]
  id?: Prisma.StringFilter<"AppointmentItem"> | string
  appointmentId?: Prisma.StringFilter<"AppointmentItem"> | string
  serviceId?: Prisma.StringFilter<"AppointmentItem"> | string
  nameFrSnapshot?: Prisma.StringFilter<"AppointmentItem"> | string
  nameHeSnapshot?: Prisma.StringFilter<"AppointmentItem"> | string
  durationMin?: Prisma.IntFilter<"AppointmentItem"> | number
  priceCents?: Prisma.IntFilter<"AppointmentItem"> | number
  appointment?: Prisma.XOR<Prisma.AppointmentScalarRelationFilter, Prisma.AppointmentWhereInput>
  service?: Prisma.XOR<Prisma.ServiceScalarRelationFilter, Prisma.ServiceWhereInput>
}

export type AppointmentItemOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  nameFrSnapshot?: Prisma.SortOrder
  nameHeSnapshot?: Prisma.SortOrder
  durationMin?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
  appointment?: Prisma.AppointmentOrderByWithRelationInput
  service?: Prisma.ServiceOrderByWithRelationInput
}

export type AppointmentItemWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AppointmentItemWhereInput | Prisma.AppointmentItemWhereInput[]
  OR?: Prisma.AppointmentItemWhereInput[]
  NOT?: Prisma.AppointmentItemWhereInput | Prisma.AppointmentItemWhereInput[]
  appointmentId?: Prisma.StringFilter<"AppointmentItem"> | string
  serviceId?: Prisma.StringFilter<"AppointmentItem"> | string
  nameFrSnapshot?: Prisma.StringFilter<"AppointmentItem"> | string
  nameHeSnapshot?: Prisma.StringFilter<"AppointmentItem"> | string
  durationMin?: Prisma.IntFilter<"AppointmentItem"> | number
  priceCents?: Prisma.IntFilter<"AppointmentItem"> | number
  appointment?: Prisma.XOR<Prisma.AppointmentScalarRelationFilter, Prisma.AppointmentWhereInput>
  service?: Prisma.XOR<Prisma.ServiceScalarRelationFilter, Prisma.ServiceWhereInput>
}, "id">

export type AppointmentItemOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  nameFrSnapshot?: Prisma.SortOrder
  nameHeSnapshot?: Prisma.SortOrder
  durationMin?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
  _count?: Prisma.AppointmentItemCountOrderByAggregateInput
  _avg?: Prisma.AppointmentItemAvgOrderByAggregateInput
  _max?: Prisma.AppointmentItemMaxOrderByAggregateInput
  _min?: Prisma.AppointmentItemMinOrderByAggregateInput
  _sum?: Prisma.AppointmentItemSumOrderByAggregateInput
}

export type AppointmentItemScalarWhereWithAggregatesInput = {
  AND?: Prisma.AppointmentItemScalarWhereWithAggregatesInput | Prisma.AppointmentItemScalarWhereWithAggregatesInput[]
  OR?: Prisma.AppointmentItemScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AppointmentItemScalarWhereWithAggregatesInput | Prisma.AppointmentItemScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AppointmentItem"> | string
  appointmentId?: Prisma.StringWithAggregatesFilter<"AppointmentItem"> | string
  serviceId?: Prisma.StringWithAggregatesFilter<"AppointmentItem"> | string
  nameFrSnapshot?: Prisma.StringWithAggregatesFilter<"AppointmentItem"> | string
  nameHeSnapshot?: Prisma.StringWithAggregatesFilter<"AppointmentItem"> | string
  durationMin?: Prisma.IntWithAggregatesFilter<"AppointmentItem"> | number
  priceCents?: Prisma.IntWithAggregatesFilter<"AppointmentItem"> | number
}

export type AppointmentItemCreateInput = {
  id?: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  durationMin: number
  priceCents: number
  appointment: Prisma.AppointmentCreateNestedOneWithoutPrestationsInput
  service: Prisma.ServiceCreateNestedOneWithoutItemsInput
}

export type AppointmentItemUncheckedCreateInput = {
  id?: string
  appointmentId: string
  serviceId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  durationMin: number
  priceCents: number
}

export type AppointmentItemUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  durationMin?: Prisma.IntFieldUpdateOperationsInput | number
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
  appointment?: Prisma.AppointmentUpdateOneRequiredWithoutPrestationsNestedInput
  service?: Prisma.ServiceUpdateOneRequiredWithoutItemsNestedInput
}

export type AppointmentItemUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  durationMin?: Prisma.IntFieldUpdateOperationsInput | number
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentItemCreateManyInput = {
  id?: string
  appointmentId: string
  serviceId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  durationMin: number
  priceCents: number
}

export type AppointmentItemUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  durationMin?: Prisma.IntFieldUpdateOperationsInput | number
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentItemUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  durationMin?: Prisma.IntFieldUpdateOperationsInput | number
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentItemListRelationFilter = {
  every?: Prisma.AppointmentItemWhereInput
  some?: Prisma.AppointmentItemWhereInput
  none?: Prisma.AppointmentItemWhereInput
}

export type AppointmentItemOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AppointmentItemCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  nameFrSnapshot?: Prisma.SortOrder
  nameHeSnapshot?: Prisma.SortOrder
  durationMin?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
}

export type AppointmentItemAvgOrderByAggregateInput = {
  durationMin?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
}

export type AppointmentItemMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  nameFrSnapshot?: Prisma.SortOrder
  nameHeSnapshot?: Prisma.SortOrder
  durationMin?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
}

export type AppointmentItemMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  serviceId?: Prisma.SortOrder
  nameFrSnapshot?: Prisma.SortOrder
  nameHeSnapshot?: Prisma.SortOrder
  durationMin?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
}

export type AppointmentItemSumOrderByAggregateInput = {
  durationMin?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
}

export type AppointmentItemCreateNestedManyWithoutServiceInput = {
  create?: Prisma.XOR<Prisma.AppointmentItemCreateWithoutServiceInput, Prisma.AppointmentItemUncheckedCreateWithoutServiceInput> | Prisma.AppointmentItemCreateWithoutServiceInput[] | Prisma.AppointmentItemUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.AppointmentItemCreateOrConnectWithoutServiceInput | Prisma.AppointmentItemCreateOrConnectWithoutServiceInput[]
  createMany?: Prisma.AppointmentItemCreateManyServiceInputEnvelope
  connect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
}

export type AppointmentItemUncheckedCreateNestedManyWithoutServiceInput = {
  create?: Prisma.XOR<Prisma.AppointmentItemCreateWithoutServiceInput, Prisma.AppointmentItemUncheckedCreateWithoutServiceInput> | Prisma.AppointmentItemCreateWithoutServiceInput[] | Prisma.AppointmentItemUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.AppointmentItemCreateOrConnectWithoutServiceInput | Prisma.AppointmentItemCreateOrConnectWithoutServiceInput[]
  createMany?: Prisma.AppointmentItemCreateManyServiceInputEnvelope
  connect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
}

export type AppointmentItemUpdateManyWithoutServiceNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentItemCreateWithoutServiceInput, Prisma.AppointmentItemUncheckedCreateWithoutServiceInput> | Prisma.AppointmentItemCreateWithoutServiceInput[] | Prisma.AppointmentItemUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.AppointmentItemCreateOrConnectWithoutServiceInput | Prisma.AppointmentItemCreateOrConnectWithoutServiceInput[]
  upsert?: Prisma.AppointmentItemUpsertWithWhereUniqueWithoutServiceInput | Prisma.AppointmentItemUpsertWithWhereUniqueWithoutServiceInput[]
  createMany?: Prisma.AppointmentItemCreateManyServiceInputEnvelope
  set?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  disconnect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  delete?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  connect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  update?: Prisma.AppointmentItemUpdateWithWhereUniqueWithoutServiceInput | Prisma.AppointmentItemUpdateWithWhereUniqueWithoutServiceInput[]
  updateMany?: Prisma.AppointmentItemUpdateManyWithWhereWithoutServiceInput | Prisma.AppointmentItemUpdateManyWithWhereWithoutServiceInput[]
  deleteMany?: Prisma.AppointmentItemScalarWhereInput | Prisma.AppointmentItemScalarWhereInput[]
}

export type AppointmentItemUncheckedUpdateManyWithoutServiceNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentItemCreateWithoutServiceInput, Prisma.AppointmentItemUncheckedCreateWithoutServiceInput> | Prisma.AppointmentItemCreateWithoutServiceInput[] | Prisma.AppointmentItemUncheckedCreateWithoutServiceInput[]
  connectOrCreate?: Prisma.AppointmentItemCreateOrConnectWithoutServiceInput | Prisma.AppointmentItemCreateOrConnectWithoutServiceInput[]
  upsert?: Prisma.AppointmentItemUpsertWithWhereUniqueWithoutServiceInput | Prisma.AppointmentItemUpsertWithWhereUniqueWithoutServiceInput[]
  createMany?: Prisma.AppointmentItemCreateManyServiceInputEnvelope
  set?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  disconnect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  delete?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  connect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  update?: Prisma.AppointmentItemUpdateWithWhereUniqueWithoutServiceInput | Prisma.AppointmentItemUpdateWithWhereUniqueWithoutServiceInput[]
  updateMany?: Prisma.AppointmentItemUpdateManyWithWhereWithoutServiceInput | Prisma.AppointmentItemUpdateManyWithWhereWithoutServiceInput[]
  deleteMany?: Prisma.AppointmentItemScalarWhereInput | Prisma.AppointmentItemScalarWhereInput[]
}

export type AppointmentItemCreateNestedManyWithoutAppointmentInput = {
  create?: Prisma.XOR<Prisma.AppointmentItemCreateWithoutAppointmentInput, Prisma.AppointmentItemUncheckedCreateWithoutAppointmentInput> | Prisma.AppointmentItemCreateWithoutAppointmentInput[] | Prisma.AppointmentItemUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AppointmentItemCreateOrConnectWithoutAppointmentInput | Prisma.AppointmentItemCreateOrConnectWithoutAppointmentInput[]
  createMany?: Prisma.AppointmentItemCreateManyAppointmentInputEnvelope
  connect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
}

export type AppointmentItemUncheckedCreateNestedManyWithoutAppointmentInput = {
  create?: Prisma.XOR<Prisma.AppointmentItemCreateWithoutAppointmentInput, Prisma.AppointmentItemUncheckedCreateWithoutAppointmentInput> | Prisma.AppointmentItemCreateWithoutAppointmentInput[] | Prisma.AppointmentItemUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AppointmentItemCreateOrConnectWithoutAppointmentInput | Prisma.AppointmentItemCreateOrConnectWithoutAppointmentInput[]
  createMany?: Prisma.AppointmentItemCreateManyAppointmentInputEnvelope
  connect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
}

export type AppointmentItemUpdateManyWithoutAppointmentNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentItemCreateWithoutAppointmentInput, Prisma.AppointmentItemUncheckedCreateWithoutAppointmentInput> | Prisma.AppointmentItemCreateWithoutAppointmentInput[] | Prisma.AppointmentItemUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AppointmentItemCreateOrConnectWithoutAppointmentInput | Prisma.AppointmentItemCreateOrConnectWithoutAppointmentInput[]
  upsert?: Prisma.AppointmentItemUpsertWithWhereUniqueWithoutAppointmentInput | Prisma.AppointmentItemUpsertWithWhereUniqueWithoutAppointmentInput[]
  createMany?: Prisma.AppointmentItemCreateManyAppointmentInputEnvelope
  set?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  disconnect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  delete?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  connect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  update?: Prisma.AppointmentItemUpdateWithWhereUniqueWithoutAppointmentInput | Prisma.AppointmentItemUpdateWithWhereUniqueWithoutAppointmentInput[]
  updateMany?: Prisma.AppointmentItemUpdateManyWithWhereWithoutAppointmentInput | Prisma.AppointmentItemUpdateManyWithWhereWithoutAppointmentInput[]
  deleteMany?: Prisma.AppointmentItemScalarWhereInput | Prisma.AppointmentItemScalarWhereInput[]
}

export type AppointmentItemUncheckedUpdateManyWithoutAppointmentNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentItemCreateWithoutAppointmentInput, Prisma.AppointmentItemUncheckedCreateWithoutAppointmentInput> | Prisma.AppointmentItemCreateWithoutAppointmentInput[] | Prisma.AppointmentItemUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AppointmentItemCreateOrConnectWithoutAppointmentInput | Prisma.AppointmentItemCreateOrConnectWithoutAppointmentInput[]
  upsert?: Prisma.AppointmentItemUpsertWithWhereUniqueWithoutAppointmentInput | Prisma.AppointmentItemUpsertWithWhereUniqueWithoutAppointmentInput[]
  createMany?: Prisma.AppointmentItemCreateManyAppointmentInputEnvelope
  set?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  disconnect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  delete?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  connect?: Prisma.AppointmentItemWhereUniqueInput | Prisma.AppointmentItemWhereUniqueInput[]
  update?: Prisma.AppointmentItemUpdateWithWhereUniqueWithoutAppointmentInput | Prisma.AppointmentItemUpdateWithWhereUniqueWithoutAppointmentInput[]
  updateMany?: Prisma.AppointmentItemUpdateManyWithWhereWithoutAppointmentInput | Prisma.AppointmentItemUpdateManyWithWhereWithoutAppointmentInput[]
  deleteMany?: Prisma.AppointmentItemScalarWhereInput | Prisma.AppointmentItemScalarWhereInput[]
}

export type AppointmentItemCreateWithoutServiceInput = {
  id?: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  durationMin: number
  priceCents: number
  appointment: Prisma.AppointmentCreateNestedOneWithoutPrestationsInput
}

export type AppointmentItemUncheckedCreateWithoutServiceInput = {
  id?: string
  appointmentId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  durationMin: number
  priceCents: number
}

export type AppointmentItemCreateOrConnectWithoutServiceInput = {
  where: Prisma.AppointmentItemWhereUniqueInput
  create: Prisma.XOR<Prisma.AppointmentItemCreateWithoutServiceInput, Prisma.AppointmentItemUncheckedCreateWithoutServiceInput>
}

export type AppointmentItemCreateManyServiceInputEnvelope = {
  data: Prisma.AppointmentItemCreateManyServiceInput | Prisma.AppointmentItemCreateManyServiceInput[]
  skipDuplicates?: boolean
}

export type AppointmentItemUpsertWithWhereUniqueWithoutServiceInput = {
  where: Prisma.AppointmentItemWhereUniqueInput
  update: Prisma.XOR<Prisma.AppointmentItemUpdateWithoutServiceInput, Prisma.AppointmentItemUncheckedUpdateWithoutServiceInput>
  create: Prisma.XOR<Prisma.AppointmentItemCreateWithoutServiceInput, Prisma.AppointmentItemUncheckedCreateWithoutServiceInput>
}

export type AppointmentItemUpdateWithWhereUniqueWithoutServiceInput = {
  where: Prisma.AppointmentItemWhereUniqueInput
  data: Prisma.XOR<Prisma.AppointmentItemUpdateWithoutServiceInput, Prisma.AppointmentItemUncheckedUpdateWithoutServiceInput>
}

export type AppointmentItemUpdateManyWithWhereWithoutServiceInput = {
  where: Prisma.AppointmentItemScalarWhereInput
  data: Prisma.XOR<Prisma.AppointmentItemUpdateManyMutationInput, Prisma.AppointmentItemUncheckedUpdateManyWithoutServiceInput>
}

export type AppointmentItemScalarWhereInput = {
  AND?: Prisma.AppointmentItemScalarWhereInput | Prisma.AppointmentItemScalarWhereInput[]
  OR?: Prisma.AppointmentItemScalarWhereInput[]
  NOT?: Prisma.AppointmentItemScalarWhereInput | Prisma.AppointmentItemScalarWhereInput[]
  id?: Prisma.StringFilter<"AppointmentItem"> | string
  appointmentId?: Prisma.StringFilter<"AppointmentItem"> | string
  serviceId?: Prisma.StringFilter<"AppointmentItem"> | string
  nameFrSnapshot?: Prisma.StringFilter<"AppointmentItem"> | string
  nameHeSnapshot?: Prisma.StringFilter<"AppointmentItem"> | string
  durationMin?: Prisma.IntFilter<"AppointmentItem"> | number
  priceCents?: Prisma.IntFilter<"AppointmentItem"> | number
}

export type AppointmentItemCreateWithoutAppointmentInput = {
  id?: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  durationMin: number
  priceCents: number
  service: Prisma.ServiceCreateNestedOneWithoutItemsInput
}

export type AppointmentItemUncheckedCreateWithoutAppointmentInput = {
  id?: string
  serviceId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  durationMin: number
  priceCents: number
}

export type AppointmentItemCreateOrConnectWithoutAppointmentInput = {
  where: Prisma.AppointmentItemWhereUniqueInput
  create: Prisma.XOR<Prisma.AppointmentItemCreateWithoutAppointmentInput, Prisma.AppointmentItemUncheckedCreateWithoutAppointmentInput>
}

export type AppointmentItemCreateManyAppointmentInputEnvelope = {
  data: Prisma.AppointmentItemCreateManyAppointmentInput | Prisma.AppointmentItemCreateManyAppointmentInput[]
  skipDuplicates?: boolean
}

export type AppointmentItemUpsertWithWhereUniqueWithoutAppointmentInput = {
  where: Prisma.AppointmentItemWhereUniqueInput
  update: Prisma.XOR<Prisma.AppointmentItemUpdateWithoutAppointmentInput, Prisma.AppointmentItemUncheckedUpdateWithoutAppointmentInput>
  create: Prisma.XOR<Prisma.AppointmentItemCreateWithoutAppointmentInput, Prisma.AppointmentItemUncheckedCreateWithoutAppointmentInput>
}

export type AppointmentItemUpdateWithWhereUniqueWithoutAppointmentInput = {
  where: Prisma.AppointmentItemWhereUniqueInput
  data: Prisma.XOR<Prisma.AppointmentItemUpdateWithoutAppointmentInput, Prisma.AppointmentItemUncheckedUpdateWithoutAppointmentInput>
}

export type AppointmentItemUpdateManyWithWhereWithoutAppointmentInput = {
  where: Prisma.AppointmentItemScalarWhereInput
  data: Prisma.XOR<Prisma.AppointmentItemUpdateManyMutationInput, Prisma.AppointmentItemUncheckedUpdateManyWithoutAppointmentInput>
}

export type AppointmentItemCreateManyServiceInput = {
  id?: string
  appointmentId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  durationMin: number
  priceCents: number
}

export type AppointmentItemUpdateWithoutServiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  durationMin?: Prisma.IntFieldUpdateOperationsInput | number
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
  appointment?: Prisma.AppointmentUpdateOneRequiredWithoutPrestationsNestedInput
}

export type AppointmentItemUncheckedUpdateWithoutServiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  durationMin?: Prisma.IntFieldUpdateOperationsInput | number
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentItemUncheckedUpdateManyWithoutServiceInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  durationMin?: Prisma.IntFieldUpdateOperationsInput | number
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentItemCreateManyAppointmentInput = {
  id?: string
  serviceId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  durationMin: number
  priceCents: number
}

export type AppointmentItemUpdateWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  durationMin?: Prisma.IntFieldUpdateOperationsInput | number
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
  service?: Prisma.ServiceUpdateOneRequiredWithoutItemsNestedInput
}

export type AppointmentItemUncheckedUpdateWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  durationMin?: Prisma.IntFieldUpdateOperationsInput | number
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentItemUncheckedUpdateManyWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  serviceId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  durationMin?: Prisma.IntFieldUpdateOperationsInput | number
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}



export type AppointmentItemSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appointmentId?: boolean
  serviceId?: boolean
  nameFrSnapshot?: boolean
  nameHeSnapshot?: boolean
  durationMin?: boolean
  priceCents?: boolean
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appointmentItem"]>

export type AppointmentItemSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appointmentId?: boolean
  serviceId?: boolean
  nameFrSnapshot?: boolean
  nameHeSnapshot?: boolean
  durationMin?: boolean
  priceCents?: boolean
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appointmentItem"]>

export type AppointmentItemSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appointmentId?: boolean
  serviceId?: boolean
  nameFrSnapshot?: boolean
  nameHeSnapshot?: boolean
  durationMin?: boolean
  priceCents?: boolean
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appointmentItem"]>

export type AppointmentItemSelectScalar = {
  id?: boolean
  appointmentId?: boolean
  serviceId?: boolean
  nameFrSnapshot?: boolean
  nameHeSnapshot?: boolean
  durationMin?: boolean
  priceCents?: boolean
}

export type AppointmentItemOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "appointmentId" | "serviceId" | "nameFrSnapshot" | "nameHeSnapshot" | "durationMin" | "priceCents", ExtArgs["result"]["appointmentItem"]>
export type AppointmentItemInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}
export type AppointmentItemIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}
export type AppointmentItemIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  service?: boolean | Prisma.ServiceDefaultArgs<ExtArgs>
}

export type $AppointmentItemPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AppointmentItem"
  objects: {
    appointment: Prisma.$AppointmentPayload<ExtArgs>
    service: Prisma.$ServicePayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    appointmentId: string
    serviceId: string
    nameFrSnapshot: string
    nameHeSnapshot: string
    durationMin: number
    priceCents: number
  }, ExtArgs["result"]["appointmentItem"]>
  composites: {}
}

export type AppointmentItemGetPayload<S extends boolean | null | undefined | AppointmentItemDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload, S>

export type AppointmentItemCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AppointmentItemFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AppointmentItemCountAggregateInputType | true
  }

export interface AppointmentItemDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AppointmentItem'], meta: { name: 'AppointmentItem' } }
  /**
   * Find zero or one AppointmentItem that matches the filter.
   * @param {AppointmentItemFindUniqueArgs} args - Arguments to find a AppointmentItem
   * @example
   * // Get one AppointmentItem
   * const appointmentItem = await prisma.appointmentItem.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AppointmentItemFindUniqueArgs>(args: Prisma.SelectSubset<T, AppointmentItemFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AppointmentItemClient<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AppointmentItem that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AppointmentItemFindUniqueOrThrowArgs} args - Arguments to find a AppointmentItem
   * @example
   * // Get one AppointmentItem
   * const appointmentItem = await prisma.appointmentItem.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AppointmentItemFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AppointmentItemFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppointmentItemClient<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppointmentItem that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentItemFindFirstArgs} args - Arguments to find a AppointmentItem
   * @example
   * // Get one AppointmentItem
   * const appointmentItem = await prisma.appointmentItem.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AppointmentItemFindFirstArgs>(args?: Prisma.SelectSubset<T, AppointmentItemFindFirstArgs<ExtArgs>>): Prisma.Prisma__AppointmentItemClient<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppointmentItem that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentItemFindFirstOrThrowArgs} args - Arguments to find a AppointmentItem
   * @example
   * // Get one AppointmentItem
   * const appointmentItem = await prisma.appointmentItem.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AppointmentItemFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AppointmentItemFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppointmentItemClient<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AppointmentItems that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentItemFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AppointmentItems
   * const appointmentItems = await prisma.appointmentItem.findMany()
   * 
   * // Get first 10 AppointmentItems
   * const appointmentItems = await prisma.appointmentItem.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const appointmentItemWithIdOnly = await prisma.appointmentItem.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AppointmentItemFindManyArgs>(args?: Prisma.SelectSubset<T, AppointmentItemFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AppointmentItem.
   * @param {AppointmentItemCreateArgs} args - Arguments to create a AppointmentItem.
   * @example
   * // Create one AppointmentItem
   * const AppointmentItem = await prisma.appointmentItem.create({
   *   data: {
   *     // ... data to create a AppointmentItem
   *   }
   * })
   * 
   */
  create<T extends AppointmentItemCreateArgs>(args: Prisma.SelectSubset<T, AppointmentItemCreateArgs<ExtArgs>>): Prisma.Prisma__AppointmentItemClient<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AppointmentItems.
   * @param {AppointmentItemCreateManyArgs} args - Arguments to create many AppointmentItems.
   * @example
   * // Create many AppointmentItems
   * const appointmentItem = await prisma.appointmentItem.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AppointmentItemCreateManyArgs>(args?: Prisma.SelectSubset<T, AppointmentItemCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AppointmentItems and returns the data saved in the database.
   * @param {AppointmentItemCreateManyAndReturnArgs} args - Arguments to create many AppointmentItems.
   * @example
   * // Create many AppointmentItems
   * const appointmentItem = await prisma.appointmentItem.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AppointmentItems and only return the `id`
   * const appointmentItemWithIdOnly = await prisma.appointmentItem.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AppointmentItemCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AppointmentItemCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AppointmentItem.
   * @param {AppointmentItemDeleteArgs} args - Arguments to delete one AppointmentItem.
   * @example
   * // Delete one AppointmentItem
   * const AppointmentItem = await prisma.appointmentItem.delete({
   *   where: {
   *     // ... filter to delete one AppointmentItem
   *   }
   * })
   * 
   */
  delete<T extends AppointmentItemDeleteArgs>(args: Prisma.SelectSubset<T, AppointmentItemDeleteArgs<ExtArgs>>): Prisma.Prisma__AppointmentItemClient<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AppointmentItem.
   * @param {AppointmentItemUpdateArgs} args - Arguments to update one AppointmentItem.
   * @example
   * // Update one AppointmentItem
   * const appointmentItem = await prisma.appointmentItem.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AppointmentItemUpdateArgs>(args: Prisma.SelectSubset<T, AppointmentItemUpdateArgs<ExtArgs>>): Prisma.Prisma__AppointmentItemClient<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AppointmentItems.
   * @param {AppointmentItemDeleteManyArgs} args - Arguments to filter AppointmentItems to delete.
   * @example
   * // Delete a few AppointmentItems
   * const { count } = await prisma.appointmentItem.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AppointmentItemDeleteManyArgs>(args?: Prisma.SelectSubset<T, AppointmentItemDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppointmentItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentItemUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AppointmentItems
   * const appointmentItem = await prisma.appointmentItem.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AppointmentItemUpdateManyArgs>(args: Prisma.SelectSubset<T, AppointmentItemUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppointmentItems and returns the data updated in the database.
   * @param {AppointmentItemUpdateManyAndReturnArgs} args - Arguments to update many AppointmentItems.
   * @example
   * // Update many AppointmentItems
   * const appointmentItem = await prisma.appointmentItem.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AppointmentItems and only return the `id`
   * const appointmentItemWithIdOnly = await prisma.appointmentItem.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AppointmentItemUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AppointmentItemUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AppointmentItem.
   * @param {AppointmentItemUpsertArgs} args - Arguments to update or create a AppointmentItem.
   * @example
   * // Update or create a AppointmentItem
   * const appointmentItem = await prisma.appointmentItem.upsert({
   *   create: {
   *     // ... data to create a AppointmentItem
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AppointmentItem we want to update
   *   }
   * })
   */
  upsert<T extends AppointmentItemUpsertArgs>(args: Prisma.SelectSubset<T, AppointmentItemUpsertArgs<ExtArgs>>): Prisma.Prisma__AppointmentItemClient<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AppointmentItems.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentItemCountArgs} args - Arguments to filter AppointmentItems to count.
   * @example
   * // Count the number of AppointmentItems
   * const count = await prisma.appointmentItem.count({
   *   where: {
   *     // ... the filter for the AppointmentItems we want to count
   *   }
   * })
  **/
  count<T extends AppointmentItemCountArgs>(
    args?: Prisma.Subset<T, AppointmentItemCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AppointmentItemCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AppointmentItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentItemAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AppointmentItemAggregateArgs>(args: Prisma.Subset<T, AppointmentItemAggregateArgs>): Prisma.PrismaPromise<GetAppointmentItemAggregateType<T>>

  /**
   * Group by AppointmentItem.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentItemGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AppointmentItemGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AppointmentItemGroupByArgs['orderBy'] }
      : { orderBy?: AppointmentItemGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AppointmentItemGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAppointmentItemGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AppointmentItem model
 */
readonly fields: AppointmentItemFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AppointmentItem.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AppointmentItemClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  appointment<T extends Prisma.AppointmentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppointmentDefaultArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  service<T extends Prisma.ServiceDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceDefaultArgs<ExtArgs>>): Prisma.Prisma__ServiceClient<runtime.Types.Result.GetResult<Prisma.$ServicePayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AppointmentItem model
 */
export interface AppointmentItemFieldRefs {
  readonly id: Prisma.FieldRef<"AppointmentItem", 'String'>
  readonly appointmentId: Prisma.FieldRef<"AppointmentItem", 'String'>
  readonly serviceId: Prisma.FieldRef<"AppointmentItem", 'String'>
  readonly nameFrSnapshot: Prisma.FieldRef<"AppointmentItem", 'String'>
  readonly nameHeSnapshot: Prisma.FieldRef<"AppointmentItem", 'String'>
  readonly durationMin: Prisma.FieldRef<"AppointmentItem", 'Int'>
  readonly priceCents: Prisma.FieldRef<"AppointmentItem", 'Int'>
}
    

// Custom InputTypes
/**
 * AppointmentItem findUnique
 */
export type AppointmentItemFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemInclude<ExtArgs> | null
  /**
   * Filter, which AppointmentItem to fetch.
   */
  where: Prisma.AppointmentItemWhereUniqueInput
}

/**
 * AppointmentItem findUniqueOrThrow
 */
export type AppointmentItemFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemInclude<ExtArgs> | null
  /**
   * Filter, which AppointmentItem to fetch.
   */
  where: Prisma.AppointmentItemWhereUniqueInput
}

/**
 * AppointmentItem findFirst
 */
export type AppointmentItemFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemInclude<ExtArgs> | null
  /**
   * Filter, which AppointmentItem to fetch.
   */
  where?: Prisma.AppointmentItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppointmentItems to fetch.
   */
  orderBy?: Prisma.AppointmentItemOrderByWithRelationInput | Prisma.AppointmentItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppointmentItems.
   */
  cursor?: Prisma.AppointmentItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppointmentItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppointmentItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppointmentItems.
   */
  distinct?: Prisma.AppointmentItemScalarFieldEnum | Prisma.AppointmentItemScalarFieldEnum[]
}

/**
 * AppointmentItem findFirstOrThrow
 */
export type AppointmentItemFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemInclude<ExtArgs> | null
  /**
   * Filter, which AppointmentItem to fetch.
   */
  where?: Prisma.AppointmentItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppointmentItems to fetch.
   */
  orderBy?: Prisma.AppointmentItemOrderByWithRelationInput | Prisma.AppointmentItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppointmentItems.
   */
  cursor?: Prisma.AppointmentItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppointmentItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppointmentItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppointmentItems.
   */
  distinct?: Prisma.AppointmentItemScalarFieldEnum | Prisma.AppointmentItemScalarFieldEnum[]
}

/**
 * AppointmentItem findMany
 */
export type AppointmentItemFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemInclude<ExtArgs> | null
  /**
   * Filter, which AppointmentItems to fetch.
   */
  where?: Prisma.AppointmentItemWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppointmentItems to fetch.
   */
  orderBy?: Prisma.AppointmentItemOrderByWithRelationInput | Prisma.AppointmentItemOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AppointmentItems.
   */
  cursor?: Prisma.AppointmentItemWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppointmentItems from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppointmentItems.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppointmentItems.
   */
  distinct?: Prisma.AppointmentItemScalarFieldEnum | Prisma.AppointmentItemScalarFieldEnum[]
}

/**
 * AppointmentItem create
 */
export type AppointmentItemCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemInclude<ExtArgs> | null
  /**
   * The data needed to create a AppointmentItem.
   */
  data: Prisma.XOR<Prisma.AppointmentItemCreateInput, Prisma.AppointmentItemUncheckedCreateInput>
}

/**
 * AppointmentItem createMany
 */
export type AppointmentItemCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AppointmentItems.
   */
  data: Prisma.AppointmentItemCreateManyInput | Prisma.AppointmentItemCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AppointmentItem createManyAndReturn
 */
export type AppointmentItemCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * The data used to create many AppointmentItems.
   */
  data: Prisma.AppointmentItemCreateManyInput | Prisma.AppointmentItemCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AppointmentItem update
 */
export type AppointmentItemUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemInclude<ExtArgs> | null
  /**
   * The data needed to update a AppointmentItem.
   */
  data: Prisma.XOR<Prisma.AppointmentItemUpdateInput, Prisma.AppointmentItemUncheckedUpdateInput>
  /**
   * Choose, which AppointmentItem to update.
   */
  where: Prisma.AppointmentItemWhereUniqueInput
}

/**
 * AppointmentItem updateMany
 */
export type AppointmentItemUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AppointmentItems.
   */
  data: Prisma.XOR<Prisma.AppointmentItemUpdateManyMutationInput, Prisma.AppointmentItemUncheckedUpdateManyInput>
  /**
   * Filter which AppointmentItems to update
   */
  where?: Prisma.AppointmentItemWhereInput
  /**
   * Limit how many AppointmentItems to update.
   */
  limit?: number
}

/**
 * AppointmentItem updateManyAndReturn
 */
export type AppointmentItemUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * The data used to update AppointmentItems.
   */
  data: Prisma.XOR<Prisma.AppointmentItemUpdateManyMutationInput, Prisma.AppointmentItemUncheckedUpdateManyInput>
  /**
   * Filter which AppointmentItems to update
   */
  where?: Prisma.AppointmentItemWhereInput
  /**
   * Limit how many AppointmentItems to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AppointmentItem upsert
 */
export type AppointmentItemUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemInclude<ExtArgs> | null
  /**
   * The filter to search for the AppointmentItem to update in case it exists.
   */
  where: Prisma.AppointmentItemWhereUniqueInput
  /**
   * In case the AppointmentItem found by the `where` argument doesn't exist, create a new AppointmentItem with this data.
   */
  create: Prisma.XOR<Prisma.AppointmentItemCreateInput, Prisma.AppointmentItemUncheckedCreateInput>
  /**
   * In case the AppointmentItem was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AppointmentItemUpdateInput, Prisma.AppointmentItemUncheckedUpdateInput>
}

/**
 * AppointmentItem delete
 */
export type AppointmentItemDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemInclude<ExtArgs> | null
  /**
   * Filter which AppointmentItem to delete.
   */
  where: Prisma.AppointmentItemWhereUniqueInput
}

/**
 * AppointmentItem deleteMany
 */
export type AppointmentItemDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppointmentItems to delete
   */
  where?: Prisma.AppointmentItemWhereInput
  /**
   * Limit how many AppointmentItems to delete.
   */
  limit?: number
}

/**
 * AppointmentItem without action
 */
export type AppointmentItemDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemInclude<ExtArgs> | null
}
