
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Appointment` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Appointment
 * 
 */
export type AppointmentModel = runtime.Types.Result.DefaultSelection<Prisma.$AppointmentPayload>

export type AggregateAppointment = {
  _count: AppointmentCountAggregateOutputType | null
  _min: AppointmentMinAggregateOutputType | null
  _max: AppointmentMaxAggregateOutputType | null
}

export type AppointmentMinAggregateOutputType = {
  id: string | null
  userId: string | null
  startsAt: Date | null
  endsAt: Date | null
  message: string | null
  status: $Enums.AppointmentStatus | null
  expiresAt: Date | null
  customerName: string | null
  customerEmail: string | null
  customerPhone: string | null
  cancelledAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AppointmentMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  startsAt: Date | null
  endsAt: Date | null
  message: string | null
  status: $Enums.AppointmentStatus | null
  expiresAt: Date | null
  customerName: string | null
  customerEmail: string | null
  customerPhone: string | null
  cancelledAt: Date | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type AppointmentCountAggregateOutputType = {
  id: number
  userId: number
  startsAt: number
  endsAt: number
  message: number
  status: number
  expiresAt: number
  customerName: number
  customerEmail: number
  customerPhone: number
  cancelledAt: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type AppointmentMinAggregateInputType = {
  id?: true
  userId?: true
  startsAt?: true
  endsAt?: true
  message?: true
  status?: true
  expiresAt?: true
  customerName?: true
  customerEmail?: true
  customerPhone?: true
  cancelledAt?: true
  createdAt?: true
  updatedAt?: true
}

export type AppointmentMaxAggregateInputType = {
  id?: true
  userId?: true
  startsAt?: true
  endsAt?: true
  message?: true
  status?: true
  expiresAt?: true
  customerName?: true
  customerEmail?: true
  customerPhone?: true
  cancelledAt?: true
  createdAt?: true
  updatedAt?: true
}

export type AppointmentCountAggregateInputType = {
  id?: true
  userId?: true
  startsAt?: true
  endsAt?: true
  message?: true
  status?: true
  expiresAt?: true
  customerName?: true
  customerEmail?: true
  customerPhone?: true
  cancelledAt?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type AppointmentAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Appointment to aggregate.
   */
  where?: Prisma.AppointmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Appointments to fetch.
   */
  orderBy?: Prisma.AppointmentOrderByWithRelationInput | Prisma.AppointmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AppointmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Appointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Appointments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Appointments
  **/
  _count?: true | AppointmentCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AppointmentMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AppointmentMaxAggregateInputType
}

export type GetAppointmentAggregateType<T extends AppointmentAggregateArgs> = {
      [P in keyof T & keyof AggregateAppointment]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAppointment[P]>
    : Prisma.GetScalarType<T[P], AggregateAppointment[P]>
}




export type AppointmentGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppointmentWhereInput
  orderBy?: Prisma.AppointmentOrderByWithAggregationInput | Prisma.AppointmentOrderByWithAggregationInput[]
  by: Prisma.AppointmentScalarFieldEnum[] | Prisma.AppointmentScalarFieldEnum
  having?: Prisma.AppointmentScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AppointmentCountAggregateInputType | true
  _min?: AppointmentMinAggregateInputType
  _max?: AppointmentMaxAggregateInputType
}

export type AppointmentGroupByOutputType = {
  id: string
  userId: string
  startsAt: Date
  endsAt: Date
  message: string | null
  status: $Enums.AppointmentStatus
  expiresAt: Date | null
  customerName: string
  customerEmail: string
  customerPhone: string
  cancelledAt: Date | null
  createdAt: Date
  updatedAt: Date
  _count: AppointmentCountAggregateOutputType | null
  _min: AppointmentMinAggregateOutputType | null
  _max: AppointmentMaxAggregateOutputType | null
}

export type GetAppointmentGroupByPayload<T extends AppointmentGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AppointmentGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AppointmentGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AppointmentGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AppointmentGroupByOutputType[P]>
      }
    >
  >



export type AppointmentWhereInput = {
  AND?: Prisma.AppointmentWhereInput | Prisma.AppointmentWhereInput[]
  OR?: Prisma.AppointmentWhereInput[]
  NOT?: Prisma.AppointmentWhereInput | Prisma.AppointmentWhereInput[]
  id?: Prisma.StringFilter<"Appointment"> | string
  userId?: Prisma.StringFilter<"Appointment"> | string
  startsAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
  endsAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
  message?: Prisma.StringNullableFilter<"Appointment"> | string | null
  status?: Prisma.EnumAppointmentStatusFilter<"Appointment"> | $Enums.AppointmentStatus
  expiresAt?: Prisma.DateTimeNullableFilter<"Appointment"> | Date | string | null
  customerName?: Prisma.StringFilter<"Appointment"> | string
  customerEmail?: Prisma.StringFilter<"Appointment"> | string
  customerPhone?: Prisma.StringFilter<"Appointment"> | string
  cancelledAt?: Prisma.DateTimeNullableFilter<"Appointment"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  prestations?: Prisma.AppointmentItemListRelationFilter
  options?: Prisma.AppointmentOptionListRelationFilter
}

export type AppointmentOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  customerName?: Prisma.SortOrder
  customerEmail?: Prisma.SortOrder
  customerPhone?: Prisma.SortOrder
  cancelledAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  prestations?: Prisma.AppointmentItemOrderByRelationAggregateInput
  options?: Prisma.AppointmentOptionOrderByRelationAggregateInput
}

export type AppointmentWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.AppointmentWhereInput | Prisma.AppointmentWhereInput[]
  OR?: Prisma.AppointmentWhereInput[]
  NOT?: Prisma.AppointmentWhereInput | Prisma.AppointmentWhereInput[]
  userId?: Prisma.StringFilter<"Appointment"> | string
  startsAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
  endsAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
  message?: Prisma.StringNullableFilter<"Appointment"> | string | null
  status?: Prisma.EnumAppointmentStatusFilter<"Appointment"> | $Enums.AppointmentStatus
  expiresAt?: Prisma.DateTimeNullableFilter<"Appointment"> | Date | string | null
  customerName?: Prisma.StringFilter<"Appointment"> | string
  customerEmail?: Prisma.StringFilter<"Appointment"> | string
  customerPhone?: Prisma.StringFilter<"Appointment"> | string
  cancelledAt?: Prisma.DateTimeNullableFilter<"Appointment"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  prestations?: Prisma.AppointmentItemListRelationFilter
  options?: Prisma.AppointmentOptionListRelationFilter
}, "id">

export type AppointmentOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  message?: Prisma.SortOrderInput | Prisma.SortOrder
  status?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrderInput | Prisma.SortOrder
  customerName?: Prisma.SortOrder
  customerEmail?: Prisma.SortOrder
  customerPhone?: Prisma.SortOrder
  cancelledAt?: Prisma.SortOrderInput | Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.AppointmentCountOrderByAggregateInput
  _max?: Prisma.AppointmentMaxOrderByAggregateInput
  _min?: Prisma.AppointmentMinOrderByAggregateInput
}

export type AppointmentScalarWhereWithAggregatesInput = {
  AND?: Prisma.AppointmentScalarWhereWithAggregatesInput | Prisma.AppointmentScalarWhereWithAggregatesInput[]
  OR?: Prisma.AppointmentScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AppointmentScalarWhereWithAggregatesInput | Prisma.AppointmentScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Appointment"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Appointment"> | string
  startsAt?: Prisma.DateTimeWithAggregatesFilter<"Appointment"> | Date | string
  endsAt?: Prisma.DateTimeWithAggregatesFilter<"Appointment"> | Date | string
  message?: Prisma.StringNullableWithAggregatesFilter<"Appointment"> | string | null
  status?: Prisma.EnumAppointmentStatusWithAggregatesFilter<"Appointment"> | $Enums.AppointmentStatus
  expiresAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Appointment"> | Date | string | null
  customerName?: Prisma.StringWithAggregatesFilter<"Appointment"> | string
  customerEmail?: Prisma.StringWithAggregatesFilter<"Appointment"> | string
  customerPhone?: Prisma.StringWithAggregatesFilter<"Appointment"> | string
  cancelledAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Appointment"> | Date | string | null
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Appointment"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Appointment"> | Date | string
}

export type AppointmentCreateInput = {
  id?: string
  startsAt: Date | string
  endsAt: Date | string
  message?: string | null
  status?: $Enums.AppointmentStatus
  expiresAt?: Date | string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  cancelledAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAppointmentsInput
  prestations?: Prisma.AppointmentItemCreateNestedManyWithoutAppointmentInput
  options?: Prisma.AppointmentOptionCreateNestedManyWithoutAppointmentInput
}

export type AppointmentUncheckedCreateInput = {
  id?: string
  userId: string
  startsAt: Date | string
  endsAt: Date | string
  message?: string | null
  status?: $Enums.AppointmentStatus
  expiresAt?: Date | string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  cancelledAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  prestations?: Prisma.AppointmentItemUncheckedCreateNestedManyWithoutAppointmentInput
  options?: Prisma.AppointmentOptionUncheckedCreateNestedManyWithoutAppointmentInput
}

export type AppointmentUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAppointmentStatusFieldUpdateOperationsInput | $Enums.AppointmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAppointmentsNestedInput
  prestations?: Prisma.AppointmentItemUpdateManyWithoutAppointmentNestedInput
  options?: Prisma.AppointmentOptionUpdateManyWithoutAppointmentNestedInput
}

export type AppointmentUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAppointmentStatusFieldUpdateOperationsInput | $Enums.AppointmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  prestations?: Prisma.AppointmentItemUncheckedUpdateManyWithoutAppointmentNestedInput
  options?: Prisma.AppointmentOptionUncheckedUpdateManyWithoutAppointmentNestedInput
}

export type AppointmentCreateManyInput = {
  id?: string
  userId: string
  startsAt: Date | string
  endsAt: Date | string
  message?: string | null
  status?: $Enums.AppointmentStatus
  expiresAt?: Date | string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  cancelledAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AppointmentUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAppointmentStatusFieldUpdateOperationsInput | $Enums.AppointmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppointmentUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAppointmentStatusFieldUpdateOperationsInput | $Enums.AppointmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type AppointmentListRelationFilter = {
  every?: Prisma.AppointmentWhereInput
  some?: Prisma.AppointmentWhereInput
  none?: Prisma.AppointmentWhereInput
}

export type AppointmentOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AppointmentCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  customerEmail?: Prisma.SortOrder
  customerPhone?: Prisma.SortOrder
  cancelledAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppointmentMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  customerEmail?: Prisma.SortOrder
  customerPhone?: Prisma.SortOrder
  cancelledAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppointmentMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  startsAt?: Prisma.SortOrder
  endsAt?: Prisma.SortOrder
  message?: Prisma.SortOrder
  status?: Prisma.SortOrder
  expiresAt?: Prisma.SortOrder
  customerName?: Prisma.SortOrder
  customerEmail?: Prisma.SortOrder
  customerPhone?: Prisma.SortOrder
  cancelledAt?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type AppointmentScalarRelationFilter = {
  is?: Prisma.AppointmentWhereInput
  isNot?: Prisma.AppointmentWhereInput
}

export type AppointmentCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AppointmentCreateWithoutUserInput, Prisma.AppointmentUncheckedCreateWithoutUserInput> | Prisma.AppointmentCreateWithoutUserInput[] | Prisma.AppointmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AppointmentCreateOrConnectWithoutUserInput | Prisma.AppointmentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AppointmentCreateManyUserInputEnvelope
  connect?: Prisma.AppointmentWhereUniqueInput | Prisma.AppointmentWhereUniqueInput[]
}

export type AppointmentUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.AppointmentCreateWithoutUserInput, Prisma.AppointmentUncheckedCreateWithoutUserInput> | Prisma.AppointmentCreateWithoutUserInput[] | Prisma.AppointmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AppointmentCreateOrConnectWithoutUserInput | Prisma.AppointmentCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.AppointmentCreateManyUserInputEnvelope
  connect?: Prisma.AppointmentWhereUniqueInput | Prisma.AppointmentWhereUniqueInput[]
}

export type AppointmentUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentCreateWithoutUserInput, Prisma.AppointmentUncheckedCreateWithoutUserInput> | Prisma.AppointmentCreateWithoutUserInput[] | Prisma.AppointmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AppointmentCreateOrConnectWithoutUserInput | Prisma.AppointmentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AppointmentUpsertWithWhereUniqueWithoutUserInput | Prisma.AppointmentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AppointmentCreateManyUserInputEnvelope
  set?: Prisma.AppointmentWhereUniqueInput | Prisma.AppointmentWhereUniqueInput[]
  disconnect?: Prisma.AppointmentWhereUniqueInput | Prisma.AppointmentWhereUniqueInput[]
  delete?: Prisma.AppointmentWhereUniqueInput | Prisma.AppointmentWhereUniqueInput[]
  connect?: Prisma.AppointmentWhereUniqueInput | Prisma.AppointmentWhereUniqueInput[]
  update?: Prisma.AppointmentUpdateWithWhereUniqueWithoutUserInput | Prisma.AppointmentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AppointmentUpdateManyWithWhereWithoutUserInput | Prisma.AppointmentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AppointmentScalarWhereInput | Prisma.AppointmentScalarWhereInput[]
}

export type AppointmentUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentCreateWithoutUserInput, Prisma.AppointmentUncheckedCreateWithoutUserInput> | Prisma.AppointmentCreateWithoutUserInput[] | Prisma.AppointmentUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.AppointmentCreateOrConnectWithoutUserInput | Prisma.AppointmentCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.AppointmentUpsertWithWhereUniqueWithoutUserInput | Prisma.AppointmentUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.AppointmentCreateManyUserInputEnvelope
  set?: Prisma.AppointmentWhereUniqueInput | Prisma.AppointmentWhereUniqueInput[]
  disconnect?: Prisma.AppointmentWhereUniqueInput | Prisma.AppointmentWhereUniqueInput[]
  delete?: Prisma.AppointmentWhereUniqueInput | Prisma.AppointmentWhereUniqueInput[]
  connect?: Prisma.AppointmentWhereUniqueInput | Prisma.AppointmentWhereUniqueInput[]
  update?: Prisma.AppointmentUpdateWithWhereUniqueWithoutUserInput | Prisma.AppointmentUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.AppointmentUpdateManyWithWhereWithoutUserInput | Prisma.AppointmentUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.AppointmentScalarWhereInput | Prisma.AppointmentScalarWhereInput[]
}

export type EnumAppointmentStatusFieldUpdateOperationsInput = {
  set?: $Enums.AppointmentStatus
}

export type AppointmentCreateNestedOneWithoutPrestationsInput = {
  create?: Prisma.XOR<Prisma.AppointmentCreateWithoutPrestationsInput, Prisma.AppointmentUncheckedCreateWithoutPrestationsInput>
  connectOrCreate?: Prisma.AppointmentCreateOrConnectWithoutPrestationsInput
  connect?: Prisma.AppointmentWhereUniqueInput
}

export type AppointmentUpdateOneRequiredWithoutPrestationsNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentCreateWithoutPrestationsInput, Prisma.AppointmentUncheckedCreateWithoutPrestationsInput>
  connectOrCreate?: Prisma.AppointmentCreateOrConnectWithoutPrestationsInput
  upsert?: Prisma.AppointmentUpsertWithoutPrestationsInput
  connect?: Prisma.AppointmentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppointmentUpdateToOneWithWhereWithoutPrestationsInput, Prisma.AppointmentUpdateWithoutPrestationsInput>, Prisma.AppointmentUncheckedUpdateWithoutPrestationsInput>
}

export type AppointmentCreateNestedOneWithoutOptionsInput = {
  create?: Prisma.XOR<Prisma.AppointmentCreateWithoutOptionsInput, Prisma.AppointmentUncheckedCreateWithoutOptionsInput>
  connectOrCreate?: Prisma.AppointmentCreateOrConnectWithoutOptionsInput
  connect?: Prisma.AppointmentWhereUniqueInput
}

export type AppointmentUpdateOneRequiredWithoutOptionsNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentCreateWithoutOptionsInput, Prisma.AppointmentUncheckedCreateWithoutOptionsInput>
  connectOrCreate?: Prisma.AppointmentCreateOrConnectWithoutOptionsInput
  upsert?: Prisma.AppointmentUpsertWithoutOptionsInput
  connect?: Prisma.AppointmentWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.AppointmentUpdateToOneWithWhereWithoutOptionsInput, Prisma.AppointmentUpdateWithoutOptionsInput>, Prisma.AppointmentUncheckedUpdateWithoutOptionsInput>
}

export type AppointmentCreateWithoutUserInput = {
  id?: string
  startsAt: Date | string
  endsAt: Date | string
  message?: string | null
  status?: $Enums.AppointmentStatus
  expiresAt?: Date | string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  cancelledAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  prestations?: Prisma.AppointmentItemCreateNestedManyWithoutAppointmentInput
  options?: Prisma.AppointmentOptionCreateNestedManyWithoutAppointmentInput
}

export type AppointmentUncheckedCreateWithoutUserInput = {
  id?: string
  startsAt: Date | string
  endsAt: Date | string
  message?: string | null
  status?: $Enums.AppointmentStatus
  expiresAt?: Date | string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  cancelledAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  prestations?: Prisma.AppointmentItemUncheckedCreateNestedManyWithoutAppointmentInput
  options?: Prisma.AppointmentOptionUncheckedCreateNestedManyWithoutAppointmentInput
}

export type AppointmentCreateOrConnectWithoutUserInput = {
  where: Prisma.AppointmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AppointmentCreateWithoutUserInput, Prisma.AppointmentUncheckedCreateWithoutUserInput>
}

export type AppointmentCreateManyUserInputEnvelope = {
  data: Prisma.AppointmentCreateManyUserInput | Prisma.AppointmentCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type AppointmentUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.AppointmentWhereUniqueInput
  update: Prisma.XOR<Prisma.AppointmentUpdateWithoutUserInput, Prisma.AppointmentUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.AppointmentCreateWithoutUserInput, Prisma.AppointmentUncheckedCreateWithoutUserInput>
}

export type AppointmentUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.AppointmentWhereUniqueInput
  data: Prisma.XOR<Prisma.AppointmentUpdateWithoutUserInput, Prisma.AppointmentUncheckedUpdateWithoutUserInput>
}

export type AppointmentUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.AppointmentScalarWhereInput
  data: Prisma.XOR<Prisma.AppointmentUpdateManyMutationInput, Prisma.AppointmentUncheckedUpdateManyWithoutUserInput>
}

export type AppointmentScalarWhereInput = {
  AND?: Prisma.AppointmentScalarWhereInput | Prisma.AppointmentScalarWhereInput[]
  OR?: Prisma.AppointmentScalarWhereInput[]
  NOT?: Prisma.AppointmentScalarWhereInput | Prisma.AppointmentScalarWhereInput[]
  id?: Prisma.StringFilter<"Appointment"> | string
  userId?: Prisma.StringFilter<"Appointment"> | string
  startsAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
  endsAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
  message?: Prisma.StringNullableFilter<"Appointment"> | string | null
  status?: Prisma.EnumAppointmentStatusFilter<"Appointment"> | $Enums.AppointmentStatus
  expiresAt?: Prisma.DateTimeNullableFilter<"Appointment"> | Date | string | null
  customerName?: Prisma.StringFilter<"Appointment"> | string
  customerEmail?: Prisma.StringFilter<"Appointment"> | string
  customerPhone?: Prisma.StringFilter<"Appointment"> | string
  cancelledAt?: Prisma.DateTimeNullableFilter<"Appointment"> | Date | string | null
  createdAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Appointment"> | Date | string
}

export type AppointmentCreateWithoutPrestationsInput = {
  id?: string
  startsAt: Date | string
  endsAt: Date | string
  message?: string | null
  status?: $Enums.AppointmentStatus
  expiresAt?: Date | string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  cancelledAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAppointmentsInput
  options?: Prisma.AppointmentOptionCreateNestedManyWithoutAppointmentInput
}

export type AppointmentUncheckedCreateWithoutPrestationsInput = {
  id?: string
  userId: string
  startsAt: Date | string
  endsAt: Date | string
  message?: string | null
  status?: $Enums.AppointmentStatus
  expiresAt?: Date | string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  cancelledAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  options?: Prisma.AppointmentOptionUncheckedCreateNestedManyWithoutAppointmentInput
}

export type AppointmentCreateOrConnectWithoutPrestationsInput = {
  where: Prisma.AppointmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AppointmentCreateWithoutPrestationsInput, Prisma.AppointmentUncheckedCreateWithoutPrestationsInput>
}

export type AppointmentUpsertWithoutPrestationsInput = {
  update: Prisma.XOR<Prisma.AppointmentUpdateWithoutPrestationsInput, Prisma.AppointmentUncheckedUpdateWithoutPrestationsInput>
  create: Prisma.XOR<Prisma.AppointmentCreateWithoutPrestationsInput, Prisma.AppointmentUncheckedCreateWithoutPrestationsInput>
  where?: Prisma.AppointmentWhereInput
}

export type AppointmentUpdateToOneWithWhereWithoutPrestationsInput = {
  where?: Prisma.AppointmentWhereInput
  data: Prisma.XOR<Prisma.AppointmentUpdateWithoutPrestationsInput, Prisma.AppointmentUncheckedUpdateWithoutPrestationsInput>
}

export type AppointmentUpdateWithoutPrestationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAppointmentStatusFieldUpdateOperationsInput | $Enums.AppointmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAppointmentsNestedInput
  options?: Prisma.AppointmentOptionUpdateManyWithoutAppointmentNestedInput
}

export type AppointmentUncheckedUpdateWithoutPrestationsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAppointmentStatusFieldUpdateOperationsInput | $Enums.AppointmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  options?: Prisma.AppointmentOptionUncheckedUpdateManyWithoutAppointmentNestedInput
}

export type AppointmentCreateWithoutOptionsInput = {
  id?: string
  startsAt: Date | string
  endsAt: Date | string
  message?: string | null
  status?: $Enums.AppointmentStatus
  expiresAt?: Date | string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  cancelledAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutAppointmentsInput
  prestations?: Prisma.AppointmentItemCreateNestedManyWithoutAppointmentInput
}

export type AppointmentUncheckedCreateWithoutOptionsInput = {
  id?: string
  userId: string
  startsAt: Date | string
  endsAt: Date | string
  message?: string | null
  status?: $Enums.AppointmentStatus
  expiresAt?: Date | string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  cancelledAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
  prestations?: Prisma.AppointmentItemUncheckedCreateNestedManyWithoutAppointmentInput
}

export type AppointmentCreateOrConnectWithoutOptionsInput = {
  where: Prisma.AppointmentWhereUniqueInput
  create: Prisma.XOR<Prisma.AppointmentCreateWithoutOptionsInput, Prisma.AppointmentUncheckedCreateWithoutOptionsInput>
}

export type AppointmentUpsertWithoutOptionsInput = {
  update: Prisma.XOR<Prisma.AppointmentUpdateWithoutOptionsInput, Prisma.AppointmentUncheckedUpdateWithoutOptionsInput>
  create: Prisma.XOR<Prisma.AppointmentCreateWithoutOptionsInput, Prisma.AppointmentUncheckedCreateWithoutOptionsInput>
  where?: Prisma.AppointmentWhereInput
}

export type AppointmentUpdateToOneWithWhereWithoutOptionsInput = {
  where?: Prisma.AppointmentWhereInput
  data: Prisma.XOR<Prisma.AppointmentUpdateWithoutOptionsInput, Prisma.AppointmentUncheckedUpdateWithoutOptionsInput>
}

export type AppointmentUpdateWithoutOptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAppointmentStatusFieldUpdateOperationsInput | $Enums.AppointmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutAppointmentsNestedInput
  prestations?: Prisma.AppointmentItemUpdateManyWithoutAppointmentNestedInput
}

export type AppointmentUncheckedUpdateWithoutOptionsInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAppointmentStatusFieldUpdateOperationsInput | $Enums.AppointmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  prestations?: Prisma.AppointmentItemUncheckedUpdateManyWithoutAppointmentNestedInput
}

export type AppointmentCreateManyUserInput = {
  id?: string
  startsAt: Date | string
  endsAt: Date | string
  message?: string | null
  status?: $Enums.AppointmentStatus
  expiresAt?: Date | string | null
  customerName: string
  customerEmail: string
  customerPhone: string
  cancelledAt?: Date | string | null
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type AppointmentUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAppointmentStatusFieldUpdateOperationsInput | $Enums.AppointmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  prestations?: Prisma.AppointmentItemUpdateManyWithoutAppointmentNestedInput
  options?: Prisma.AppointmentOptionUpdateManyWithoutAppointmentNestedInput
}

export type AppointmentUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAppointmentStatusFieldUpdateOperationsInput | $Enums.AppointmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  prestations?: Prisma.AppointmentItemUncheckedUpdateManyWithoutAppointmentNestedInput
  options?: Prisma.AppointmentOptionUncheckedUpdateManyWithoutAppointmentNestedInput
}

export type AppointmentUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  startsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  endsAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  message?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  status?: Prisma.EnumAppointmentStatusFieldUpdateOperationsInput | $Enums.AppointmentStatus
  expiresAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  customerName?: Prisma.StringFieldUpdateOperationsInput | string
  customerEmail?: Prisma.StringFieldUpdateOperationsInput | string
  customerPhone?: Prisma.StringFieldUpdateOperationsInput | string
  cancelledAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}


/**
 * Count Type AppointmentCountOutputType
 */

export type AppointmentCountOutputType = {
  prestations: number
  options: number
}

export type AppointmentCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  prestations?: boolean | AppointmentCountOutputTypeCountPrestationsArgs
  options?: boolean | AppointmentCountOutputTypeCountOptionsArgs
}

/**
 * AppointmentCountOutputType without action
 */
export type AppointmentCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentCountOutputType
   */
  select?: Prisma.AppointmentCountOutputTypeSelect<ExtArgs> | null
}

/**
 * AppointmentCountOutputType without action
 */
export type AppointmentCountOutputTypeCountPrestationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppointmentItemWhereInput
}

/**
 * AppointmentCountOutputType without action
 */
export type AppointmentCountOutputTypeCountOptionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppointmentOptionWhereInput
}


export type AppointmentSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  startsAt?: boolean
  endsAt?: boolean
  message?: boolean
  status?: boolean
  expiresAt?: boolean
  customerName?: boolean
  customerEmail?: boolean
  customerPhone?: boolean
  cancelledAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  prestations?: boolean | Prisma.Appointment$prestationsArgs<ExtArgs>
  options?: boolean | Prisma.Appointment$optionsArgs<ExtArgs>
  _count?: boolean | Prisma.AppointmentCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appointment"]>

export type AppointmentSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  startsAt?: boolean
  endsAt?: boolean
  message?: boolean
  status?: boolean
  expiresAt?: boolean
  customerName?: boolean
  customerEmail?: boolean
  customerPhone?: boolean
  cancelledAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appointment"]>

export type AppointmentSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  startsAt?: boolean
  endsAt?: boolean
  message?: boolean
  status?: boolean
  expiresAt?: boolean
  customerName?: boolean
  customerEmail?: boolean
  customerPhone?: boolean
  cancelledAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appointment"]>

export type AppointmentSelectScalar = {
  id?: boolean
  userId?: boolean
  startsAt?: boolean
  endsAt?: boolean
  message?: boolean
  status?: boolean
  expiresAt?: boolean
  customerName?: boolean
  customerEmail?: boolean
  customerPhone?: boolean
  cancelledAt?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type AppointmentOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "startsAt" | "endsAt" | "message" | "status" | "expiresAt" | "customerName" | "customerEmail" | "customerPhone" | "cancelledAt" | "createdAt" | "updatedAt", ExtArgs["result"]["appointment"]>
export type AppointmentInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  prestations?: boolean | Prisma.Appointment$prestationsArgs<ExtArgs>
  options?: boolean | Prisma.Appointment$optionsArgs<ExtArgs>
  _count?: boolean | Prisma.AppointmentCountOutputTypeDefaultArgs<ExtArgs>
}
export type AppointmentIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type AppointmentIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $AppointmentPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Appointment"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    prestations: Prisma.$AppointmentItemPayload<ExtArgs>[]
    options: Prisma.$AppointmentOptionPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    startsAt: Date
    endsAt: Date
    message: string | null
    status: $Enums.AppointmentStatus
    expiresAt: Date | null
    customerName: string
    customerEmail: string
    customerPhone: string
    cancelledAt: Date | null
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["appointment"]>
  composites: {}
}

export type AppointmentGetPayload<S extends boolean | null | undefined | AppointmentDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AppointmentPayload, S>

export type AppointmentCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AppointmentFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AppointmentCountAggregateInputType | true
  }

export interface AppointmentDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Appointment'], meta: { name: 'Appointment' } }
  /**
   * Find zero or one Appointment that matches the filter.
   * @param {AppointmentFindUniqueArgs} args - Arguments to find a Appointment
   * @example
   * // Get one Appointment
   * const appointment = await prisma.appointment.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AppointmentFindUniqueArgs>(args: Prisma.SelectSubset<T, AppointmentFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Appointment that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AppointmentFindUniqueOrThrowArgs} args - Arguments to find a Appointment
   * @example
   * // Get one Appointment
   * const appointment = await prisma.appointment.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AppointmentFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AppointmentFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Appointment that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentFindFirstArgs} args - Arguments to find a Appointment
   * @example
   * // Get one Appointment
   * const appointment = await prisma.appointment.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AppointmentFindFirstArgs>(args?: Prisma.SelectSubset<T, AppointmentFindFirstArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Appointment that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentFindFirstOrThrowArgs} args - Arguments to find a Appointment
   * @example
   * // Get one Appointment
   * const appointment = await prisma.appointment.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AppointmentFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AppointmentFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Appointments that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Appointments
   * const appointments = await prisma.appointment.findMany()
   * 
   * // Get first 10 Appointments
   * const appointments = await prisma.appointment.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const appointmentWithIdOnly = await prisma.appointment.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AppointmentFindManyArgs>(args?: Prisma.SelectSubset<T, AppointmentFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Appointment.
   * @param {AppointmentCreateArgs} args - Arguments to create a Appointment.
   * @example
   * // Create one Appointment
   * const Appointment = await prisma.appointment.create({
   *   data: {
   *     // ... data to create a Appointment
   *   }
   * })
   * 
   */
  create<T extends AppointmentCreateArgs>(args: Prisma.SelectSubset<T, AppointmentCreateArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Appointments.
   * @param {AppointmentCreateManyArgs} args - Arguments to create many Appointments.
   * @example
   * // Create many Appointments
   * const appointment = await prisma.appointment.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AppointmentCreateManyArgs>(args?: Prisma.SelectSubset<T, AppointmentCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Appointments and returns the data saved in the database.
   * @param {AppointmentCreateManyAndReturnArgs} args - Arguments to create many Appointments.
   * @example
   * // Create many Appointments
   * const appointment = await prisma.appointment.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Appointments and only return the `id`
   * const appointmentWithIdOnly = await prisma.appointment.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AppointmentCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AppointmentCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Appointment.
   * @param {AppointmentDeleteArgs} args - Arguments to delete one Appointment.
   * @example
   * // Delete one Appointment
   * const Appointment = await prisma.appointment.delete({
   *   where: {
   *     // ... filter to delete one Appointment
   *   }
   * })
   * 
   */
  delete<T extends AppointmentDeleteArgs>(args: Prisma.SelectSubset<T, AppointmentDeleteArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Appointment.
   * @param {AppointmentUpdateArgs} args - Arguments to update one Appointment.
   * @example
   * // Update one Appointment
   * const appointment = await prisma.appointment.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AppointmentUpdateArgs>(args: Prisma.SelectSubset<T, AppointmentUpdateArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Appointments.
   * @param {AppointmentDeleteManyArgs} args - Arguments to filter Appointments to delete.
   * @example
   * // Delete a few Appointments
   * const { count } = await prisma.appointment.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AppointmentDeleteManyArgs>(args?: Prisma.SelectSubset<T, AppointmentDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Appointments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Appointments
   * const appointment = await prisma.appointment.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AppointmentUpdateManyArgs>(args: Prisma.SelectSubset<T, AppointmentUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Appointments and returns the data updated in the database.
   * @param {AppointmentUpdateManyAndReturnArgs} args - Arguments to update many Appointments.
   * @example
   * // Update many Appointments
   * const appointment = await prisma.appointment.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Appointments and only return the `id`
   * const appointmentWithIdOnly = await prisma.appointment.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AppointmentUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AppointmentUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Appointment.
   * @param {AppointmentUpsertArgs} args - Arguments to update or create a Appointment.
   * @example
   * // Update or create a Appointment
   * const appointment = await prisma.appointment.upsert({
   *   create: {
   *     // ... data to create a Appointment
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Appointment we want to update
   *   }
   * })
   */
  upsert<T extends AppointmentUpsertArgs>(args: Prisma.SelectSubset<T, AppointmentUpsertArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Appointments.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentCountArgs} args - Arguments to filter Appointments to count.
   * @example
   * // Count the number of Appointments
   * const count = await prisma.appointment.count({
   *   where: {
   *     // ... the filter for the Appointments we want to count
   *   }
   * })
  **/
  count<T extends AppointmentCountArgs>(
    args?: Prisma.Subset<T, AppointmentCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AppointmentCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Appointment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AppointmentAggregateArgs>(args: Prisma.Subset<T, AppointmentAggregateArgs>): Prisma.PrismaPromise<GetAppointmentAggregateType<T>>

  /**
   * Group by Appointment.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AppointmentGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AppointmentGroupByArgs['orderBy'] }
      : { orderBy?: AppointmentGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AppointmentGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAppointmentGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Appointment model
 */
readonly fields: AppointmentFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Appointment.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AppointmentClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  prestations<T extends Prisma.Appointment$prestationsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Appointment$prestationsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentItemPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  options<T extends Prisma.Appointment$optionsArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Appointment$optionsArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Appointment model
 */
export interface AppointmentFieldRefs {
  readonly id: Prisma.FieldRef<"Appointment", 'String'>
  readonly userId: Prisma.FieldRef<"Appointment", 'String'>
  readonly startsAt: Prisma.FieldRef<"Appointment", 'DateTime'>
  readonly endsAt: Prisma.FieldRef<"Appointment", 'DateTime'>
  readonly message: Prisma.FieldRef<"Appointment", 'String'>
  readonly status: Prisma.FieldRef<"Appointment", 'AppointmentStatus'>
  readonly expiresAt: Prisma.FieldRef<"Appointment", 'DateTime'>
  readonly customerName: Prisma.FieldRef<"Appointment", 'String'>
  readonly customerEmail: Prisma.FieldRef<"Appointment", 'String'>
  readonly customerPhone: Prisma.FieldRef<"Appointment", 'String'>
  readonly cancelledAt: Prisma.FieldRef<"Appointment", 'DateTime'>
  readonly createdAt: Prisma.FieldRef<"Appointment", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Appointment", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Appointment findUnique
 */
export type AppointmentFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  /**
   * Filter, which Appointment to fetch.
   */
  where: Prisma.AppointmentWhereUniqueInput
}

/**
 * Appointment findUniqueOrThrow
 */
export type AppointmentFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  /**
   * Filter, which Appointment to fetch.
   */
  where: Prisma.AppointmentWhereUniqueInput
}

/**
 * Appointment findFirst
 */
export type AppointmentFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  /**
   * Filter, which Appointment to fetch.
   */
  where?: Prisma.AppointmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Appointments to fetch.
   */
  orderBy?: Prisma.AppointmentOrderByWithRelationInput | Prisma.AppointmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Appointments.
   */
  cursor?: Prisma.AppointmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Appointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Appointments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Appointments.
   */
  distinct?: Prisma.AppointmentScalarFieldEnum | Prisma.AppointmentScalarFieldEnum[]
}

/**
 * Appointment findFirstOrThrow
 */
export type AppointmentFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  /**
   * Filter, which Appointment to fetch.
   */
  where?: Prisma.AppointmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Appointments to fetch.
   */
  orderBy?: Prisma.AppointmentOrderByWithRelationInput | Prisma.AppointmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Appointments.
   */
  cursor?: Prisma.AppointmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Appointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Appointments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Appointments.
   */
  distinct?: Prisma.AppointmentScalarFieldEnum | Prisma.AppointmentScalarFieldEnum[]
}

/**
 * Appointment findMany
 */
export type AppointmentFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  /**
   * Filter, which Appointments to fetch.
   */
  where?: Prisma.AppointmentWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Appointments to fetch.
   */
  orderBy?: Prisma.AppointmentOrderByWithRelationInput | Prisma.AppointmentOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Appointments.
   */
  cursor?: Prisma.AppointmentWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Appointments from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Appointments.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Appointments.
   */
  distinct?: Prisma.AppointmentScalarFieldEnum | Prisma.AppointmentScalarFieldEnum[]
}

/**
 * Appointment create
 */
export type AppointmentCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  /**
   * The data needed to create a Appointment.
   */
  data: Prisma.XOR<Prisma.AppointmentCreateInput, Prisma.AppointmentUncheckedCreateInput>
}

/**
 * Appointment createMany
 */
export type AppointmentCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Appointments.
   */
  data: Prisma.AppointmentCreateManyInput | Prisma.AppointmentCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Appointment createManyAndReturn
 */
export type AppointmentCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * The data used to create many Appointments.
   */
  data: Prisma.AppointmentCreateManyInput | Prisma.AppointmentCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Appointment update
 */
export type AppointmentUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  /**
   * The data needed to update a Appointment.
   */
  data: Prisma.XOR<Prisma.AppointmentUpdateInput, Prisma.AppointmentUncheckedUpdateInput>
  /**
   * Choose, which Appointment to update.
   */
  where: Prisma.AppointmentWhereUniqueInput
}

/**
 * Appointment updateMany
 */
export type AppointmentUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Appointments.
   */
  data: Prisma.XOR<Prisma.AppointmentUpdateManyMutationInput, Prisma.AppointmentUncheckedUpdateManyInput>
  /**
   * Filter which Appointments to update
   */
  where?: Prisma.AppointmentWhereInput
  /**
   * Limit how many Appointments to update.
   */
  limit?: number
}

/**
 * Appointment updateManyAndReturn
 */
export type AppointmentUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * The data used to update Appointments.
   */
  data: Prisma.XOR<Prisma.AppointmentUpdateManyMutationInput, Prisma.AppointmentUncheckedUpdateManyInput>
  /**
   * Filter which Appointments to update
   */
  where?: Prisma.AppointmentWhereInput
  /**
   * Limit how many Appointments to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Appointment upsert
 */
export type AppointmentUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  /**
   * The filter to search for the Appointment to update in case it exists.
   */
  where: Prisma.AppointmentWhereUniqueInput
  /**
   * In case the Appointment found by the `where` argument doesn't exist, create a new Appointment with this data.
   */
  create: Prisma.XOR<Prisma.AppointmentCreateInput, Prisma.AppointmentUncheckedCreateInput>
  /**
   * In case the Appointment was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AppointmentUpdateInput, Prisma.AppointmentUncheckedUpdateInput>
}

/**
 * Appointment delete
 */
export type AppointmentDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
  /**
   * Filter which Appointment to delete.
   */
  where: Prisma.AppointmentWhereUniqueInput
}

/**
 * Appointment deleteMany
 */
export type AppointmentDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Appointments to delete
   */
  where?: Prisma.AppointmentWhereInput
  /**
   * Limit how many Appointments to delete.
   */
  limit?: number
}

/**
 * Appointment.prestations
 */
export type Appointment$prestationsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentItem
   */
  select?: Prisma.AppointmentItemSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentItem
   */
  omit?: Prisma.AppointmentItemOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentItemInclude<ExtArgs> | null
  where?: Prisma.AppointmentItemWhereInput
  orderBy?: Prisma.AppointmentItemOrderByWithRelationInput | Prisma.AppointmentItemOrderByWithRelationInput[]
  cursor?: Prisma.AppointmentItemWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentItemScalarFieldEnum | Prisma.AppointmentItemScalarFieldEnum[]
}

/**
 * Appointment.options
 */
export type Appointment$optionsArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionInclude<ExtArgs> | null
  where?: Prisma.AppointmentOptionWhereInput
  orderBy?: Prisma.AppointmentOptionOrderByWithRelationInput | Prisma.AppointmentOptionOrderByWithRelationInput[]
  cursor?: Prisma.AppointmentOptionWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AppointmentOptionScalarFieldEnum | Prisma.AppointmentOptionScalarFieldEnum[]
}

/**
 * Appointment without action
 */
export type AppointmentDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Appointment
   */
  select?: Prisma.AppointmentSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Appointment
   */
  omit?: Prisma.AppointmentOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentInclude<ExtArgs> | null
}
