
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `AppointmentOption` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model AppointmentOption
 * 
 */
export type AppointmentOptionModel = runtime.Types.Result.DefaultSelection<Prisma.$AppointmentOptionPayload>

export type AggregateAppointmentOption = {
  _count: AppointmentOptionCountAggregateOutputType | null
  _avg: AppointmentOptionAvgAggregateOutputType | null
  _sum: AppointmentOptionSumAggregateOutputType | null
  _min: AppointmentOptionMinAggregateOutputType | null
  _max: AppointmentOptionMaxAggregateOutputType | null
}

export type AppointmentOptionAvgAggregateOutputType = {
  priceCents: number | null
}

export type AppointmentOptionSumAggregateOutputType = {
  priceCents: number | null
}

export type AppointmentOptionMinAggregateOutputType = {
  id: string | null
  appointmentId: string | null
  optionId: string | null
  nameFrSnapshot: string | null
  nameHeSnapshot: string | null
  priceCents: number | null
}

export type AppointmentOptionMaxAggregateOutputType = {
  id: string | null
  appointmentId: string | null
  optionId: string | null
  nameFrSnapshot: string | null
  nameHeSnapshot: string | null
  priceCents: number | null
}

export type AppointmentOptionCountAggregateOutputType = {
  id: number
  appointmentId: number
  optionId: number
  nameFrSnapshot: number
  nameHeSnapshot: number
  priceCents: number
  _all: number
}


export type AppointmentOptionAvgAggregateInputType = {
  priceCents?: true
}

export type AppointmentOptionSumAggregateInputType = {
  priceCents?: true
}

export type AppointmentOptionMinAggregateInputType = {
  id?: true
  appointmentId?: true
  optionId?: true
  nameFrSnapshot?: true
  nameHeSnapshot?: true
  priceCents?: true
}

export type AppointmentOptionMaxAggregateInputType = {
  id?: true
  appointmentId?: true
  optionId?: true
  nameFrSnapshot?: true
  nameHeSnapshot?: true
  priceCents?: true
}

export type AppointmentOptionCountAggregateInputType = {
  id?: true
  appointmentId?: true
  optionId?: true
  nameFrSnapshot?: true
  nameHeSnapshot?: true
  priceCents?: true
  _all?: true
}

export type AppointmentOptionAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppointmentOption to aggregate.
   */
  where?: Prisma.AppointmentOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppointmentOptions to fetch.
   */
  orderBy?: Prisma.AppointmentOptionOrderByWithRelationInput | Prisma.AppointmentOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.AppointmentOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppointmentOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppointmentOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned AppointmentOptions
  **/
  _count?: true | AppointmentOptionCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: AppointmentOptionAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: AppointmentOptionSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: AppointmentOptionMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: AppointmentOptionMaxAggregateInputType
}

export type GetAppointmentOptionAggregateType<T extends AppointmentOptionAggregateArgs> = {
      [P in keyof T & keyof AggregateAppointmentOption]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateAppointmentOption[P]>
    : Prisma.GetScalarType<T[P], AggregateAppointmentOption[P]>
}




export type AppointmentOptionGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AppointmentOptionWhereInput
  orderBy?: Prisma.AppointmentOptionOrderByWithAggregationInput | Prisma.AppointmentOptionOrderByWithAggregationInput[]
  by: Prisma.AppointmentOptionScalarFieldEnum[] | Prisma.AppointmentOptionScalarFieldEnum
  having?: Prisma.AppointmentOptionScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: AppointmentOptionCountAggregateInputType | true
  _avg?: AppointmentOptionAvgAggregateInputType
  _sum?: AppointmentOptionSumAggregateInputType
  _min?: AppointmentOptionMinAggregateInputType
  _max?: AppointmentOptionMaxAggregateInputType
}

export type AppointmentOptionGroupByOutputType = {
  id: string
  appointmentId: string
  optionId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  priceCents: number
  _count: AppointmentOptionCountAggregateOutputType | null
  _avg: AppointmentOptionAvgAggregateOutputType | null
  _sum: AppointmentOptionSumAggregateOutputType | null
  _min: AppointmentOptionMinAggregateOutputType | null
  _max: AppointmentOptionMaxAggregateOutputType | null
}

export type GetAppointmentOptionGroupByPayload<T extends AppointmentOptionGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<AppointmentOptionGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof AppointmentOptionGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], AppointmentOptionGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], AppointmentOptionGroupByOutputType[P]>
      }
    >
  >



export type AppointmentOptionWhereInput = {
  AND?: Prisma.AppointmentOptionWhereInput | Prisma.AppointmentOptionWhereInput[]
  OR?: Prisma.AppointmentOptionWhereInput[]
  NOT?: Prisma.AppointmentOptionWhereInput | Prisma.AppointmentOptionWhereInput[]
  id?: Prisma.StringFilter<"AppointmentOption"> | string
  appointmentId?: Prisma.StringFilter<"AppointmentOption"> | string
  optionId?: Prisma.StringFilter<"AppointmentOption"> | string
  nameFrSnapshot?: Prisma.StringFilter<"AppointmentOption"> | string
  nameHeSnapshot?: Prisma.StringFilter<"AppointmentOption"> | string
  priceCents?: Prisma.IntFilter<"AppointmentOption"> | number
  appointment?: Prisma.XOR<Prisma.AppointmentScalarRelationFilter, Prisma.AppointmentWhereInput>
  option?: Prisma.XOR<Prisma.ServiceOptionScalarRelationFilter, Prisma.ServiceOptionWhereInput>
}

export type AppointmentOptionOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  optionId?: Prisma.SortOrder
  nameFrSnapshot?: Prisma.SortOrder
  nameHeSnapshot?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
  appointment?: Prisma.AppointmentOrderByWithRelationInput
  option?: Prisma.ServiceOptionOrderByWithRelationInput
}

export type AppointmentOptionWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  appointmentId_optionId?: Prisma.AppointmentOptionAppointmentIdOptionIdCompoundUniqueInput
  AND?: Prisma.AppointmentOptionWhereInput | Prisma.AppointmentOptionWhereInput[]
  OR?: Prisma.AppointmentOptionWhereInput[]
  NOT?: Prisma.AppointmentOptionWhereInput | Prisma.AppointmentOptionWhereInput[]
  appointmentId?: Prisma.StringFilter<"AppointmentOption"> | string
  optionId?: Prisma.StringFilter<"AppointmentOption"> | string
  nameFrSnapshot?: Prisma.StringFilter<"AppointmentOption"> | string
  nameHeSnapshot?: Prisma.StringFilter<"AppointmentOption"> | string
  priceCents?: Prisma.IntFilter<"AppointmentOption"> | number
  appointment?: Prisma.XOR<Prisma.AppointmentScalarRelationFilter, Prisma.AppointmentWhereInput>
  option?: Prisma.XOR<Prisma.ServiceOptionScalarRelationFilter, Prisma.ServiceOptionWhereInput>
}, "id" | "appointmentId_optionId">

export type AppointmentOptionOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  optionId?: Prisma.SortOrder
  nameFrSnapshot?: Prisma.SortOrder
  nameHeSnapshot?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
  _count?: Prisma.AppointmentOptionCountOrderByAggregateInput
  _avg?: Prisma.AppointmentOptionAvgOrderByAggregateInput
  _max?: Prisma.AppointmentOptionMaxOrderByAggregateInput
  _min?: Prisma.AppointmentOptionMinOrderByAggregateInput
  _sum?: Prisma.AppointmentOptionSumOrderByAggregateInput
}

export type AppointmentOptionScalarWhereWithAggregatesInput = {
  AND?: Prisma.AppointmentOptionScalarWhereWithAggregatesInput | Prisma.AppointmentOptionScalarWhereWithAggregatesInput[]
  OR?: Prisma.AppointmentOptionScalarWhereWithAggregatesInput[]
  NOT?: Prisma.AppointmentOptionScalarWhereWithAggregatesInput | Prisma.AppointmentOptionScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"AppointmentOption"> | string
  appointmentId?: Prisma.StringWithAggregatesFilter<"AppointmentOption"> | string
  optionId?: Prisma.StringWithAggregatesFilter<"AppointmentOption"> | string
  nameFrSnapshot?: Prisma.StringWithAggregatesFilter<"AppointmentOption"> | string
  nameHeSnapshot?: Prisma.StringWithAggregatesFilter<"AppointmentOption"> | string
  priceCents?: Prisma.IntWithAggregatesFilter<"AppointmentOption"> | number
}

export type AppointmentOptionCreateInput = {
  id?: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  priceCents: number
  appointment: Prisma.AppointmentCreateNestedOneWithoutOptionsInput
  option: Prisma.ServiceOptionCreateNestedOneWithoutOptionInput
}

export type AppointmentOptionUncheckedCreateInput = {
  id?: string
  appointmentId: string
  optionId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  priceCents: number
}

export type AppointmentOptionUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
  appointment?: Prisma.AppointmentUpdateOneRequiredWithoutOptionsNestedInput
  option?: Prisma.ServiceOptionUpdateOneRequiredWithoutOptionNestedInput
}

export type AppointmentOptionUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  optionId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentOptionCreateManyInput = {
  id?: string
  appointmentId: string
  optionId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  priceCents: number
}

export type AppointmentOptionUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentOptionUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  optionId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentOptionListRelationFilter = {
  every?: Prisma.AppointmentOptionWhereInput
  some?: Prisma.AppointmentOptionWhereInput
  none?: Prisma.AppointmentOptionWhereInput
}

export type AppointmentOptionOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type AppointmentOptionAppointmentIdOptionIdCompoundUniqueInput = {
  appointmentId: string
  optionId: string
}

export type AppointmentOptionCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  optionId?: Prisma.SortOrder
  nameFrSnapshot?: Prisma.SortOrder
  nameHeSnapshot?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
}

export type AppointmentOptionAvgOrderByAggregateInput = {
  priceCents?: Prisma.SortOrder
}

export type AppointmentOptionMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  optionId?: Prisma.SortOrder
  nameFrSnapshot?: Prisma.SortOrder
  nameHeSnapshot?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
}

export type AppointmentOptionMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  appointmentId?: Prisma.SortOrder
  optionId?: Prisma.SortOrder
  nameFrSnapshot?: Prisma.SortOrder
  nameHeSnapshot?: Prisma.SortOrder
  priceCents?: Prisma.SortOrder
}

export type AppointmentOptionSumOrderByAggregateInput = {
  priceCents?: Prisma.SortOrder
}

export type AppointmentOptionCreateNestedManyWithoutOptionInput = {
  create?: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutOptionInput, Prisma.AppointmentOptionUncheckedCreateWithoutOptionInput> | Prisma.AppointmentOptionCreateWithoutOptionInput[] | Prisma.AppointmentOptionUncheckedCreateWithoutOptionInput[]
  connectOrCreate?: Prisma.AppointmentOptionCreateOrConnectWithoutOptionInput | Prisma.AppointmentOptionCreateOrConnectWithoutOptionInput[]
  createMany?: Prisma.AppointmentOptionCreateManyOptionInputEnvelope
  connect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
}

export type AppointmentOptionUncheckedCreateNestedManyWithoutOptionInput = {
  create?: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutOptionInput, Prisma.AppointmentOptionUncheckedCreateWithoutOptionInput> | Prisma.AppointmentOptionCreateWithoutOptionInput[] | Prisma.AppointmentOptionUncheckedCreateWithoutOptionInput[]
  connectOrCreate?: Prisma.AppointmentOptionCreateOrConnectWithoutOptionInput | Prisma.AppointmentOptionCreateOrConnectWithoutOptionInput[]
  createMany?: Prisma.AppointmentOptionCreateManyOptionInputEnvelope
  connect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
}

export type AppointmentOptionUpdateManyWithoutOptionNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutOptionInput, Prisma.AppointmentOptionUncheckedCreateWithoutOptionInput> | Prisma.AppointmentOptionCreateWithoutOptionInput[] | Prisma.AppointmentOptionUncheckedCreateWithoutOptionInput[]
  connectOrCreate?: Prisma.AppointmentOptionCreateOrConnectWithoutOptionInput | Prisma.AppointmentOptionCreateOrConnectWithoutOptionInput[]
  upsert?: Prisma.AppointmentOptionUpsertWithWhereUniqueWithoutOptionInput | Prisma.AppointmentOptionUpsertWithWhereUniqueWithoutOptionInput[]
  createMany?: Prisma.AppointmentOptionCreateManyOptionInputEnvelope
  set?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  disconnect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  delete?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  connect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  update?: Prisma.AppointmentOptionUpdateWithWhereUniqueWithoutOptionInput | Prisma.AppointmentOptionUpdateWithWhereUniqueWithoutOptionInput[]
  updateMany?: Prisma.AppointmentOptionUpdateManyWithWhereWithoutOptionInput | Prisma.AppointmentOptionUpdateManyWithWhereWithoutOptionInput[]
  deleteMany?: Prisma.AppointmentOptionScalarWhereInput | Prisma.AppointmentOptionScalarWhereInput[]
}

export type AppointmentOptionUncheckedUpdateManyWithoutOptionNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutOptionInput, Prisma.AppointmentOptionUncheckedCreateWithoutOptionInput> | Prisma.AppointmentOptionCreateWithoutOptionInput[] | Prisma.AppointmentOptionUncheckedCreateWithoutOptionInput[]
  connectOrCreate?: Prisma.AppointmentOptionCreateOrConnectWithoutOptionInput | Prisma.AppointmentOptionCreateOrConnectWithoutOptionInput[]
  upsert?: Prisma.AppointmentOptionUpsertWithWhereUniqueWithoutOptionInput | Prisma.AppointmentOptionUpsertWithWhereUniqueWithoutOptionInput[]
  createMany?: Prisma.AppointmentOptionCreateManyOptionInputEnvelope
  set?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  disconnect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  delete?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  connect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  update?: Prisma.AppointmentOptionUpdateWithWhereUniqueWithoutOptionInput | Prisma.AppointmentOptionUpdateWithWhereUniqueWithoutOptionInput[]
  updateMany?: Prisma.AppointmentOptionUpdateManyWithWhereWithoutOptionInput | Prisma.AppointmentOptionUpdateManyWithWhereWithoutOptionInput[]
  deleteMany?: Prisma.AppointmentOptionScalarWhereInput | Prisma.AppointmentOptionScalarWhereInput[]
}

export type AppointmentOptionCreateNestedManyWithoutAppointmentInput = {
  create?: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutAppointmentInput, Prisma.AppointmentOptionUncheckedCreateWithoutAppointmentInput> | Prisma.AppointmentOptionCreateWithoutAppointmentInput[] | Prisma.AppointmentOptionUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AppointmentOptionCreateOrConnectWithoutAppointmentInput | Prisma.AppointmentOptionCreateOrConnectWithoutAppointmentInput[]
  createMany?: Prisma.AppointmentOptionCreateManyAppointmentInputEnvelope
  connect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
}

export type AppointmentOptionUncheckedCreateNestedManyWithoutAppointmentInput = {
  create?: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutAppointmentInput, Prisma.AppointmentOptionUncheckedCreateWithoutAppointmentInput> | Prisma.AppointmentOptionCreateWithoutAppointmentInput[] | Prisma.AppointmentOptionUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AppointmentOptionCreateOrConnectWithoutAppointmentInput | Prisma.AppointmentOptionCreateOrConnectWithoutAppointmentInput[]
  createMany?: Prisma.AppointmentOptionCreateManyAppointmentInputEnvelope
  connect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
}

export type AppointmentOptionUpdateManyWithoutAppointmentNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutAppointmentInput, Prisma.AppointmentOptionUncheckedCreateWithoutAppointmentInput> | Prisma.AppointmentOptionCreateWithoutAppointmentInput[] | Prisma.AppointmentOptionUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AppointmentOptionCreateOrConnectWithoutAppointmentInput | Prisma.AppointmentOptionCreateOrConnectWithoutAppointmentInput[]
  upsert?: Prisma.AppointmentOptionUpsertWithWhereUniqueWithoutAppointmentInput | Prisma.AppointmentOptionUpsertWithWhereUniqueWithoutAppointmentInput[]
  createMany?: Prisma.AppointmentOptionCreateManyAppointmentInputEnvelope
  set?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  disconnect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  delete?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  connect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  update?: Prisma.AppointmentOptionUpdateWithWhereUniqueWithoutAppointmentInput | Prisma.AppointmentOptionUpdateWithWhereUniqueWithoutAppointmentInput[]
  updateMany?: Prisma.AppointmentOptionUpdateManyWithWhereWithoutAppointmentInput | Prisma.AppointmentOptionUpdateManyWithWhereWithoutAppointmentInput[]
  deleteMany?: Prisma.AppointmentOptionScalarWhereInput | Prisma.AppointmentOptionScalarWhereInput[]
}

export type AppointmentOptionUncheckedUpdateManyWithoutAppointmentNestedInput = {
  create?: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutAppointmentInput, Prisma.AppointmentOptionUncheckedCreateWithoutAppointmentInput> | Prisma.AppointmentOptionCreateWithoutAppointmentInput[] | Prisma.AppointmentOptionUncheckedCreateWithoutAppointmentInput[]
  connectOrCreate?: Prisma.AppointmentOptionCreateOrConnectWithoutAppointmentInput | Prisma.AppointmentOptionCreateOrConnectWithoutAppointmentInput[]
  upsert?: Prisma.AppointmentOptionUpsertWithWhereUniqueWithoutAppointmentInput | Prisma.AppointmentOptionUpsertWithWhereUniqueWithoutAppointmentInput[]
  createMany?: Prisma.AppointmentOptionCreateManyAppointmentInputEnvelope
  set?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  disconnect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  delete?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  connect?: Prisma.AppointmentOptionWhereUniqueInput | Prisma.AppointmentOptionWhereUniqueInput[]
  update?: Prisma.AppointmentOptionUpdateWithWhereUniqueWithoutAppointmentInput | Prisma.AppointmentOptionUpdateWithWhereUniqueWithoutAppointmentInput[]
  updateMany?: Prisma.AppointmentOptionUpdateManyWithWhereWithoutAppointmentInput | Prisma.AppointmentOptionUpdateManyWithWhereWithoutAppointmentInput[]
  deleteMany?: Prisma.AppointmentOptionScalarWhereInput | Prisma.AppointmentOptionScalarWhereInput[]
}

export type AppointmentOptionCreateWithoutOptionInput = {
  id?: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  priceCents: number
  appointment: Prisma.AppointmentCreateNestedOneWithoutOptionsInput
}

export type AppointmentOptionUncheckedCreateWithoutOptionInput = {
  id?: string
  appointmentId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  priceCents: number
}

export type AppointmentOptionCreateOrConnectWithoutOptionInput = {
  where: Prisma.AppointmentOptionWhereUniqueInput
  create: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutOptionInput, Prisma.AppointmentOptionUncheckedCreateWithoutOptionInput>
}

export type AppointmentOptionCreateManyOptionInputEnvelope = {
  data: Prisma.AppointmentOptionCreateManyOptionInput | Prisma.AppointmentOptionCreateManyOptionInput[]
  skipDuplicates?: boolean
}

export type AppointmentOptionUpsertWithWhereUniqueWithoutOptionInput = {
  where: Prisma.AppointmentOptionWhereUniqueInput
  update: Prisma.XOR<Prisma.AppointmentOptionUpdateWithoutOptionInput, Prisma.AppointmentOptionUncheckedUpdateWithoutOptionInput>
  create: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutOptionInput, Prisma.AppointmentOptionUncheckedCreateWithoutOptionInput>
}

export type AppointmentOptionUpdateWithWhereUniqueWithoutOptionInput = {
  where: Prisma.AppointmentOptionWhereUniqueInput
  data: Prisma.XOR<Prisma.AppointmentOptionUpdateWithoutOptionInput, Prisma.AppointmentOptionUncheckedUpdateWithoutOptionInput>
}

export type AppointmentOptionUpdateManyWithWhereWithoutOptionInput = {
  where: Prisma.AppointmentOptionScalarWhereInput
  data: Prisma.XOR<Prisma.AppointmentOptionUpdateManyMutationInput, Prisma.AppointmentOptionUncheckedUpdateManyWithoutOptionInput>
}

export type AppointmentOptionScalarWhereInput = {
  AND?: Prisma.AppointmentOptionScalarWhereInput | Prisma.AppointmentOptionScalarWhereInput[]
  OR?: Prisma.AppointmentOptionScalarWhereInput[]
  NOT?: Prisma.AppointmentOptionScalarWhereInput | Prisma.AppointmentOptionScalarWhereInput[]
  id?: Prisma.StringFilter<"AppointmentOption"> | string
  appointmentId?: Prisma.StringFilter<"AppointmentOption"> | string
  optionId?: Prisma.StringFilter<"AppointmentOption"> | string
  nameFrSnapshot?: Prisma.StringFilter<"AppointmentOption"> | string
  nameHeSnapshot?: Prisma.StringFilter<"AppointmentOption"> | string
  priceCents?: Prisma.IntFilter<"AppointmentOption"> | number
}

export type AppointmentOptionCreateWithoutAppointmentInput = {
  id?: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  priceCents: number
  option: Prisma.ServiceOptionCreateNestedOneWithoutOptionInput
}

export type AppointmentOptionUncheckedCreateWithoutAppointmentInput = {
  id?: string
  optionId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  priceCents: number
}

export type AppointmentOptionCreateOrConnectWithoutAppointmentInput = {
  where: Prisma.AppointmentOptionWhereUniqueInput
  create: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutAppointmentInput, Prisma.AppointmentOptionUncheckedCreateWithoutAppointmentInput>
}

export type AppointmentOptionCreateManyAppointmentInputEnvelope = {
  data: Prisma.AppointmentOptionCreateManyAppointmentInput | Prisma.AppointmentOptionCreateManyAppointmentInput[]
  skipDuplicates?: boolean
}

export type AppointmentOptionUpsertWithWhereUniqueWithoutAppointmentInput = {
  where: Prisma.AppointmentOptionWhereUniqueInput
  update: Prisma.XOR<Prisma.AppointmentOptionUpdateWithoutAppointmentInput, Prisma.AppointmentOptionUncheckedUpdateWithoutAppointmentInput>
  create: Prisma.XOR<Prisma.AppointmentOptionCreateWithoutAppointmentInput, Prisma.AppointmentOptionUncheckedCreateWithoutAppointmentInput>
}

export type AppointmentOptionUpdateWithWhereUniqueWithoutAppointmentInput = {
  where: Prisma.AppointmentOptionWhereUniqueInput
  data: Prisma.XOR<Prisma.AppointmentOptionUpdateWithoutAppointmentInput, Prisma.AppointmentOptionUncheckedUpdateWithoutAppointmentInput>
}

export type AppointmentOptionUpdateManyWithWhereWithoutAppointmentInput = {
  where: Prisma.AppointmentOptionScalarWhereInput
  data: Prisma.XOR<Prisma.AppointmentOptionUpdateManyMutationInput, Prisma.AppointmentOptionUncheckedUpdateManyWithoutAppointmentInput>
}

export type AppointmentOptionCreateManyOptionInput = {
  id?: string
  appointmentId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  priceCents: number
}

export type AppointmentOptionUpdateWithoutOptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
  appointment?: Prisma.AppointmentUpdateOneRequiredWithoutOptionsNestedInput
}

export type AppointmentOptionUncheckedUpdateWithoutOptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentOptionUncheckedUpdateManyWithoutOptionInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  appointmentId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentOptionCreateManyAppointmentInput = {
  id?: string
  optionId: string
  nameFrSnapshot: string
  nameHeSnapshot: string
  priceCents: number
}

export type AppointmentOptionUpdateWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
  option?: Prisma.ServiceOptionUpdateOneRequiredWithoutOptionNestedInput
}

export type AppointmentOptionUncheckedUpdateWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  optionId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}

export type AppointmentOptionUncheckedUpdateManyWithoutAppointmentInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  optionId?: Prisma.StringFieldUpdateOperationsInput | string
  nameFrSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  nameHeSnapshot?: Prisma.StringFieldUpdateOperationsInput | string
  priceCents?: Prisma.IntFieldUpdateOperationsInput | number
}



export type AppointmentOptionSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appointmentId?: boolean
  optionId?: boolean
  nameFrSnapshot?: boolean
  nameHeSnapshot?: boolean
  priceCents?: boolean
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  option?: boolean | Prisma.ServiceOptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appointmentOption"]>

export type AppointmentOptionSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appointmentId?: boolean
  optionId?: boolean
  nameFrSnapshot?: boolean
  nameHeSnapshot?: boolean
  priceCents?: boolean
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  option?: boolean | Prisma.ServiceOptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appointmentOption"]>

export type AppointmentOptionSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  appointmentId?: boolean
  optionId?: boolean
  nameFrSnapshot?: boolean
  nameHeSnapshot?: boolean
  priceCents?: boolean
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  option?: boolean | Prisma.ServiceOptionDefaultArgs<ExtArgs>
}, ExtArgs["result"]["appointmentOption"]>

export type AppointmentOptionSelectScalar = {
  id?: boolean
  appointmentId?: boolean
  optionId?: boolean
  nameFrSnapshot?: boolean
  nameHeSnapshot?: boolean
  priceCents?: boolean
}

export type AppointmentOptionOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "appointmentId" | "optionId" | "nameFrSnapshot" | "nameHeSnapshot" | "priceCents", ExtArgs["result"]["appointmentOption"]>
export type AppointmentOptionInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  option?: boolean | Prisma.ServiceOptionDefaultArgs<ExtArgs>
}
export type AppointmentOptionIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  option?: boolean | Prisma.ServiceOptionDefaultArgs<ExtArgs>
}
export type AppointmentOptionIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  appointment?: boolean | Prisma.AppointmentDefaultArgs<ExtArgs>
  option?: boolean | Prisma.ServiceOptionDefaultArgs<ExtArgs>
}

export type $AppointmentOptionPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "AppointmentOption"
  objects: {
    appointment: Prisma.$AppointmentPayload<ExtArgs>
    option: Prisma.$ServiceOptionPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    appointmentId: string
    optionId: string
    nameFrSnapshot: string
    nameHeSnapshot: string
    priceCents: number
  }, ExtArgs["result"]["appointmentOption"]>
  composites: {}
}

export type AppointmentOptionGetPayload<S extends boolean | null | undefined | AppointmentOptionDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload, S>

export type AppointmentOptionCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<AppointmentOptionFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: AppointmentOptionCountAggregateInputType | true
  }

export interface AppointmentOptionDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['AppointmentOption'], meta: { name: 'AppointmentOption' } }
  /**
   * Find zero or one AppointmentOption that matches the filter.
   * @param {AppointmentOptionFindUniqueArgs} args - Arguments to find a AppointmentOption
   * @example
   * // Get one AppointmentOption
   * const appointmentOption = await prisma.appointmentOption.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends AppointmentOptionFindUniqueArgs>(args: Prisma.SelectSubset<T, AppointmentOptionFindUniqueArgs<ExtArgs>>): Prisma.Prisma__AppointmentOptionClient<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one AppointmentOption that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {AppointmentOptionFindUniqueOrThrowArgs} args - Arguments to find a AppointmentOption
   * @example
   * // Get one AppointmentOption
   * const appointmentOption = await prisma.appointmentOption.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends AppointmentOptionFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, AppointmentOptionFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppointmentOptionClient<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppointmentOption that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentOptionFindFirstArgs} args - Arguments to find a AppointmentOption
   * @example
   * // Get one AppointmentOption
   * const appointmentOption = await prisma.appointmentOption.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends AppointmentOptionFindFirstArgs>(args?: Prisma.SelectSubset<T, AppointmentOptionFindFirstArgs<ExtArgs>>): Prisma.Prisma__AppointmentOptionClient<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first AppointmentOption that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentOptionFindFirstOrThrowArgs} args - Arguments to find a AppointmentOption
   * @example
   * // Get one AppointmentOption
   * const appointmentOption = await prisma.appointmentOption.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends AppointmentOptionFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, AppointmentOptionFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__AppointmentOptionClient<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more AppointmentOptions that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentOptionFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all AppointmentOptions
   * const appointmentOptions = await prisma.appointmentOption.findMany()
   * 
   * // Get first 10 AppointmentOptions
   * const appointmentOptions = await prisma.appointmentOption.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const appointmentOptionWithIdOnly = await prisma.appointmentOption.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends AppointmentOptionFindManyArgs>(args?: Prisma.SelectSubset<T, AppointmentOptionFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a AppointmentOption.
   * @param {AppointmentOptionCreateArgs} args - Arguments to create a AppointmentOption.
   * @example
   * // Create one AppointmentOption
   * const AppointmentOption = await prisma.appointmentOption.create({
   *   data: {
   *     // ... data to create a AppointmentOption
   *   }
   * })
   * 
   */
  create<T extends AppointmentOptionCreateArgs>(args: Prisma.SelectSubset<T, AppointmentOptionCreateArgs<ExtArgs>>): Prisma.Prisma__AppointmentOptionClient<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many AppointmentOptions.
   * @param {AppointmentOptionCreateManyArgs} args - Arguments to create many AppointmentOptions.
   * @example
   * // Create many AppointmentOptions
   * const appointmentOption = await prisma.appointmentOption.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends AppointmentOptionCreateManyArgs>(args?: Prisma.SelectSubset<T, AppointmentOptionCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many AppointmentOptions and returns the data saved in the database.
   * @param {AppointmentOptionCreateManyAndReturnArgs} args - Arguments to create many AppointmentOptions.
   * @example
   * // Create many AppointmentOptions
   * const appointmentOption = await prisma.appointmentOption.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many AppointmentOptions and only return the `id`
   * const appointmentOptionWithIdOnly = await prisma.appointmentOption.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends AppointmentOptionCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, AppointmentOptionCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a AppointmentOption.
   * @param {AppointmentOptionDeleteArgs} args - Arguments to delete one AppointmentOption.
   * @example
   * // Delete one AppointmentOption
   * const AppointmentOption = await prisma.appointmentOption.delete({
   *   where: {
   *     // ... filter to delete one AppointmentOption
   *   }
   * })
   * 
   */
  delete<T extends AppointmentOptionDeleteArgs>(args: Prisma.SelectSubset<T, AppointmentOptionDeleteArgs<ExtArgs>>): Prisma.Prisma__AppointmentOptionClient<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one AppointmentOption.
   * @param {AppointmentOptionUpdateArgs} args - Arguments to update one AppointmentOption.
   * @example
   * // Update one AppointmentOption
   * const appointmentOption = await prisma.appointmentOption.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends AppointmentOptionUpdateArgs>(args: Prisma.SelectSubset<T, AppointmentOptionUpdateArgs<ExtArgs>>): Prisma.Prisma__AppointmentOptionClient<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more AppointmentOptions.
   * @param {AppointmentOptionDeleteManyArgs} args - Arguments to filter AppointmentOptions to delete.
   * @example
   * // Delete a few AppointmentOptions
   * const { count } = await prisma.appointmentOption.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends AppointmentOptionDeleteManyArgs>(args?: Prisma.SelectSubset<T, AppointmentOptionDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppointmentOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentOptionUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many AppointmentOptions
   * const appointmentOption = await prisma.appointmentOption.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends AppointmentOptionUpdateManyArgs>(args: Prisma.SelectSubset<T, AppointmentOptionUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more AppointmentOptions and returns the data updated in the database.
   * @param {AppointmentOptionUpdateManyAndReturnArgs} args - Arguments to update many AppointmentOptions.
   * @example
   * // Update many AppointmentOptions
   * const appointmentOption = await prisma.appointmentOption.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more AppointmentOptions and only return the `id`
   * const appointmentOptionWithIdOnly = await prisma.appointmentOption.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends AppointmentOptionUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, AppointmentOptionUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one AppointmentOption.
   * @param {AppointmentOptionUpsertArgs} args - Arguments to update or create a AppointmentOption.
   * @example
   * // Update or create a AppointmentOption
   * const appointmentOption = await prisma.appointmentOption.upsert({
   *   create: {
   *     // ... data to create a AppointmentOption
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the AppointmentOption we want to update
   *   }
   * })
   */
  upsert<T extends AppointmentOptionUpsertArgs>(args: Prisma.SelectSubset<T, AppointmentOptionUpsertArgs<ExtArgs>>): Prisma.Prisma__AppointmentOptionClient<runtime.Types.Result.GetResult<Prisma.$AppointmentOptionPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of AppointmentOptions.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentOptionCountArgs} args - Arguments to filter AppointmentOptions to count.
   * @example
   * // Count the number of AppointmentOptions
   * const count = await prisma.appointmentOption.count({
   *   where: {
   *     // ... the filter for the AppointmentOptions we want to count
   *   }
   * })
  **/
  count<T extends AppointmentOptionCountArgs>(
    args?: Prisma.Subset<T, AppointmentOptionCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], AppointmentOptionCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a AppointmentOption.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentOptionAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends AppointmentOptionAggregateArgs>(args: Prisma.Subset<T, AppointmentOptionAggregateArgs>): Prisma.PrismaPromise<GetAppointmentOptionAggregateType<T>>

  /**
   * Group by AppointmentOption.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {AppointmentOptionGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends AppointmentOptionGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: AppointmentOptionGroupByArgs['orderBy'] }
      : { orderBy?: AppointmentOptionGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, AppointmentOptionGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetAppointmentOptionGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the AppointmentOption model
 */
readonly fields: AppointmentOptionFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for AppointmentOption.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__AppointmentOptionClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  appointment<T extends Prisma.AppointmentDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.AppointmentDefaultArgs<ExtArgs>>): Prisma.Prisma__AppointmentClient<runtime.Types.Result.GetResult<Prisma.$AppointmentPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  option<T extends Prisma.ServiceOptionDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ServiceOptionDefaultArgs<ExtArgs>>): Prisma.Prisma__ServiceOptionClient<runtime.Types.Result.GetResult<Prisma.$ServiceOptionPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the AppointmentOption model
 */
export interface AppointmentOptionFieldRefs {
  readonly id: Prisma.FieldRef<"AppointmentOption", 'String'>
  readonly appointmentId: Prisma.FieldRef<"AppointmentOption", 'String'>
  readonly optionId: Prisma.FieldRef<"AppointmentOption", 'String'>
  readonly nameFrSnapshot: Prisma.FieldRef<"AppointmentOption", 'String'>
  readonly nameHeSnapshot: Prisma.FieldRef<"AppointmentOption", 'String'>
  readonly priceCents: Prisma.FieldRef<"AppointmentOption", 'Int'>
}
    

// Custom InputTypes
/**
 * AppointmentOption findUnique
 */
export type AppointmentOptionFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionInclude<ExtArgs> | null
  /**
   * Filter, which AppointmentOption to fetch.
   */
  where: Prisma.AppointmentOptionWhereUniqueInput
}

/**
 * AppointmentOption findUniqueOrThrow
 */
export type AppointmentOptionFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionInclude<ExtArgs> | null
  /**
   * Filter, which AppointmentOption to fetch.
   */
  where: Prisma.AppointmentOptionWhereUniqueInput
}

/**
 * AppointmentOption findFirst
 */
export type AppointmentOptionFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionInclude<ExtArgs> | null
  /**
   * Filter, which AppointmentOption to fetch.
   */
  where?: Prisma.AppointmentOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppointmentOptions to fetch.
   */
  orderBy?: Prisma.AppointmentOptionOrderByWithRelationInput | Prisma.AppointmentOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppointmentOptions.
   */
  cursor?: Prisma.AppointmentOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppointmentOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppointmentOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppointmentOptions.
   */
  distinct?: Prisma.AppointmentOptionScalarFieldEnum | Prisma.AppointmentOptionScalarFieldEnum[]
}

/**
 * AppointmentOption findFirstOrThrow
 */
export type AppointmentOptionFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionInclude<ExtArgs> | null
  /**
   * Filter, which AppointmentOption to fetch.
   */
  where?: Prisma.AppointmentOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppointmentOptions to fetch.
   */
  orderBy?: Prisma.AppointmentOptionOrderByWithRelationInput | Prisma.AppointmentOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for AppointmentOptions.
   */
  cursor?: Prisma.AppointmentOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppointmentOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppointmentOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppointmentOptions.
   */
  distinct?: Prisma.AppointmentOptionScalarFieldEnum | Prisma.AppointmentOptionScalarFieldEnum[]
}

/**
 * AppointmentOption findMany
 */
export type AppointmentOptionFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionInclude<ExtArgs> | null
  /**
   * Filter, which AppointmentOptions to fetch.
   */
  where?: Prisma.AppointmentOptionWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of AppointmentOptions to fetch.
   */
  orderBy?: Prisma.AppointmentOptionOrderByWithRelationInput | Prisma.AppointmentOptionOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing AppointmentOptions.
   */
  cursor?: Prisma.AppointmentOptionWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` AppointmentOptions from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` AppointmentOptions.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of AppointmentOptions.
   */
  distinct?: Prisma.AppointmentOptionScalarFieldEnum | Prisma.AppointmentOptionScalarFieldEnum[]
}

/**
 * AppointmentOption create
 */
export type AppointmentOptionCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionInclude<ExtArgs> | null
  /**
   * The data needed to create a AppointmentOption.
   */
  data: Prisma.XOR<Prisma.AppointmentOptionCreateInput, Prisma.AppointmentOptionUncheckedCreateInput>
}

/**
 * AppointmentOption createMany
 */
export type AppointmentOptionCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many AppointmentOptions.
   */
  data: Prisma.AppointmentOptionCreateManyInput | Prisma.AppointmentOptionCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * AppointmentOption createManyAndReturn
 */
export type AppointmentOptionCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * The data used to create many AppointmentOptions.
   */
  data: Prisma.AppointmentOptionCreateManyInput | Prisma.AppointmentOptionCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * AppointmentOption update
 */
export type AppointmentOptionUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionInclude<ExtArgs> | null
  /**
   * The data needed to update a AppointmentOption.
   */
  data: Prisma.XOR<Prisma.AppointmentOptionUpdateInput, Prisma.AppointmentOptionUncheckedUpdateInput>
  /**
   * Choose, which AppointmentOption to update.
   */
  where: Prisma.AppointmentOptionWhereUniqueInput
}

/**
 * AppointmentOption updateMany
 */
export type AppointmentOptionUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update AppointmentOptions.
   */
  data: Prisma.XOR<Prisma.AppointmentOptionUpdateManyMutationInput, Prisma.AppointmentOptionUncheckedUpdateManyInput>
  /**
   * Filter which AppointmentOptions to update
   */
  where?: Prisma.AppointmentOptionWhereInput
  /**
   * Limit how many AppointmentOptions to update.
   */
  limit?: number
}

/**
 * AppointmentOption updateManyAndReturn
 */
export type AppointmentOptionUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * The data used to update AppointmentOptions.
   */
  data: Prisma.XOR<Prisma.AppointmentOptionUpdateManyMutationInput, Prisma.AppointmentOptionUncheckedUpdateManyInput>
  /**
   * Filter which AppointmentOptions to update
   */
  where?: Prisma.AppointmentOptionWhereInput
  /**
   * Limit how many AppointmentOptions to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * AppointmentOption upsert
 */
export type AppointmentOptionUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionInclude<ExtArgs> | null
  /**
   * The filter to search for the AppointmentOption to update in case it exists.
   */
  where: Prisma.AppointmentOptionWhereUniqueInput
  /**
   * In case the AppointmentOption found by the `where` argument doesn't exist, create a new AppointmentOption with this data.
   */
  create: Prisma.XOR<Prisma.AppointmentOptionCreateInput, Prisma.AppointmentOptionUncheckedCreateInput>
  /**
   * In case the AppointmentOption was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.AppointmentOptionUpdateInput, Prisma.AppointmentOptionUncheckedUpdateInput>
}

/**
 * AppointmentOption delete
 */
export type AppointmentOptionDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionInclude<ExtArgs> | null
  /**
   * Filter which AppointmentOption to delete.
   */
  where: Prisma.AppointmentOptionWhereUniqueInput
}

/**
 * AppointmentOption deleteMany
 */
export type AppointmentOptionDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which AppointmentOptions to delete
   */
  where?: Prisma.AppointmentOptionWhereInput
  /**
   * Limit how many AppointmentOptions to delete.
   */
  limit?: number
}

/**
 * AppointmentOption without action
 */
export type AppointmentOptionDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the AppointmentOption
   */
  select?: Prisma.AppointmentOptionSelect<ExtArgs> | null
  /**
   * Omit specific fields from the AppointmentOption
   */
  omit?: Prisma.AppointmentOptionOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AppointmentOptionInclude<ExtArgs> | null
}
