
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Prestations` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Prestations
 * 
 */
export type PrestationsModel = runtime.Types.Result.DefaultSelection<Prisma.$PrestationsPayload>

export type AggregatePrestations = {
  _count: PrestationsCountAggregateOutputType | null
  _avg: PrestationsAvgAggregateOutputType | null
  _sum: PrestationsSumAggregateOutputType | null
  _min: PrestationsMinAggregateOutputType | null
  _max: PrestationsMaxAggregateOutputType | null
}

export type PrestationsAvgAggregateOutputType = {
  price: number | null
}

export type PrestationsSumAggregateOutputType = {
  price: number | null
}

export type PrestationsMinAggregateOutputType = {
  id: string | null
  name: string | null
  price: number | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PrestationsMaxAggregateOutputType = {
  id: string | null
  name: string | null
  price: number | null
  isActive: boolean | null
  createdAt: Date | null
  updatedAt: Date | null
}

export type PrestationsCountAggregateOutputType = {
  id: number
  name: number
  price: number
  isActive: number
  createdAt: number
  updatedAt: number
  _all: number
}


export type PrestationsAvgAggregateInputType = {
  price?: true
}

export type PrestationsSumAggregateInputType = {
  price?: true
}

export type PrestationsMinAggregateInputType = {
  id?: true
  name?: true
  price?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PrestationsMaxAggregateInputType = {
  id?: true
  name?: true
  price?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
}

export type PrestationsCountAggregateInputType = {
  id?: true
  name?: true
  price?: true
  isActive?: true
  createdAt?: true
  updatedAt?: true
  _all?: true
}

export type PrestationsAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Prestations to aggregate.
   */
  where?: Prisma.PrestationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Prestations to fetch.
   */
  orderBy?: Prisma.PrestationsOrderByWithRelationInput | Prisma.PrestationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PrestationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Prestations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Prestations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Prestations
  **/
  _count?: true | PrestationsCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PrestationsAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PrestationsSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PrestationsMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PrestationsMaxAggregateInputType
}

export type GetPrestationsAggregateType<T extends PrestationsAggregateArgs> = {
      [P in keyof T & keyof AggregatePrestations]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePrestations[P]>
    : Prisma.GetScalarType<T[P], AggregatePrestations[P]>
}




export type PrestationsGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PrestationsWhereInput
  orderBy?: Prisma.PrestationsOrderByWithAggregationInput | Prisma.PrestationsOrderByWithAggregationInput[]
  by: Prisma.PrestationsScalarFieldEnum[] | Prisma.PrestationsScalarFieldEnum
  having?: Prisma.PrestationsScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PrestationsCountAggregateInputType | true
  _avg?: PrestationsAvgAggregateInputType
  _sum?: PrestationsSumAggregateInputType
  _min?: PrestationsMinAggregateInputType
  _max?: PrestationsMaxAggregateInputType
}

export type PrestationsGroupByOutputType = {
  id: string
  name: string
  price: number
  isActive: boolean
  createdAt: Date
  updatedAt: Date
  _count: PrestationsCountAggregateOutputType | null
  _avg: PrestationsAvgAggregateOutputType | null
  _sum: PrestationsSumAggregateOutputType | null
  _min: PrestationsMinAggregateOutputType | null
  _max: PrestationsMaxAggregateOutputType | null
}

export type GetPrestationsGroupByPayload<T extends PrestationsGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PrestationsGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PrestationsGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PrestationsGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PrestationsGroupByOutputType[P]>
      }
    >
  >



export type PrestationsWhereInput = {
  AND?: Prisma.PrestationsWhereInput | Prisma.PrestationsWhereInput[]
  OR?: Prisma.PrestationsWhereInput[]
  NOT?: Prisma.PrestationsWhereInput | Prisma.PrestationsWhereInput[]
  id?: Prisma.StringFilter<"Prestations"> | string
  name?: Prisma.StringFilter<"Prestations"> | string
  price?: Prisma.IntFilter<"Prestations"> | number
  isActive?: Prisma.BoolFilter<"Prestations"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Prestations"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Prestations"> | Date | string
}

export type PrestationsOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrestationsWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PrestationsWhereInput | Prisma.PrestationsWhereInput[]
  OR?: Prisma.PrestationsWhereInput[]
  NOT?: Prisma.PrestationsWhereInput | Prisma.PrestationsWhereInput[]
  name?: Prisma.StringFilter<"Prestations"> | string
  price?: Prisma.IntFilter<"Prestations"> | number
  isActive?: Prisma.BoolFilter<"Prestations"> | boolean
  createdAt?: Prisma.DateTimeFilter<"Prestations"> | Date | string
  updatedAt?: Prisma.DateTimeFilter<"Prestations"> | Date | string
}, "id">

export type PrestationsOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.PrestationsCountOrderByAggregateInput
  _avg?: Prisma.PrestationsAvgOrderByAggregateInput
  _max?: Prisma.PrestationsMaxOrderByAggregateInput
  _min?: Prisma.PrestationsMinOrderByAggregateInput
  _sum?: Prisma.PrestationsSumOrderByAggregateInput
}

export type PrestationsScalarWhereWithAggregatesInput = {
  AND?: Prisma.PrestationsScalarWhereWithAggregatesInput | Prisma.PrestationsScalarWhereWithAggregatesInput[]
  OR?: Prisma.PrestationsScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PrestationsScalarWhereWithAggregatesInput | Prisma.PrestationsScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Prestations"> | string
  name?: Prisma.StringWithAggregatesFilter<"Prestations"> | string
  price?: Prisma.IntWithAggregatesFilter<"Prestations"> | number
  isActive?: Prisma.BoolWithAggregatesFilter<"Prestations"> | boolean
  createdAt?: Prisma.DateTimeWithAggregatesFilter<"Prestations"> | Date | string
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"Prestations"> | Date | string
}

export type PrestationsCreateInput = {
  id?: string
  name: string
  price: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrestationsUncheckedCreateInput = {
  id?: string
  name: string
  price: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrestationsUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrestationsUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrestationsCreateManyInput = {
  id?: string
  name: string
  price: number
  isActive?: boolean
  createdAt?: Date | string
  updatedAt?: Date | string
}

export type PrestationsUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrestationsUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  name?: Prisma.StringFieldUpdateOperationsInput | string
  price?: Prisma.IntFieldUpdateOperationsInput | number
  isActive?: Prisma.BoolFieldUpdateOperationsInput | boolean
  createdAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type PrestationsCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrestationsAvgOrderByAggregateInput = {
  price?: Prisma.SortOrder
}

export type PrestationsMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrestationsMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  name?: Prisma.SortOrder
  price?: Prisma.SortOrder
  isActive?: Prisma.SortOrder
  createdAt?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type PrestationsSumOrderByAggregateInput = {
  price?: Prisma.SortOrder
}



export type PrestationsSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["prestations"]>

export type PrestationsSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["prestations"]>

export type PrestationsSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  name?: boolean
  price?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}, ExtArgs["result"]["prestations"]>

export type PrestationsSelectScalar = {
  id?: boolean
  name?: boolean
  price?: boolean
  isActive?: boolean
  createdAt?: boolean
  updatedAt?: boolean
}

export type PrestationsOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "name" | "price" | "isActive" | "createdAt" | "updatedAt", ExtArgs["result"]["prestations"]>

export type $PrestationsPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Prestations"
  objects: {}
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    name: string
    price: number
    isActive: boolean
    createdAt: Date
    updatedAt: Date
  }, ExtArgs["result"]["prestations"]>
  composites: {}
}

export type PrestationsGetPayload<S extends boolean | null | undefined | PrestationsDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PrestationsPayload, S>

export type PrestationsCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PrestationsFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PrestationsCountAggregateInputType | true
  }

export interface PrestationsDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Prestations'], meta: { name: 'Prestations' } }
  /**
   * Find zero or one Prestations that matches the filter.
   * @param {PrestationsFindUniqueArgs} args - Arguments to find a Prestations
   * @example
   * // Get one Prestations
   * const prestations = await prisma.prestations.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PrestationsFindUniqueArgs>(args: Prisma.SelectSubset<T, PrestationsFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PrestationsClient<runtime.Types.Result.GetResult<Prisma.$PrestationsPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Prestations that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PrestationsFindUniqueOrThrowArgs} args - Arguments to find a Prestations
   * @example
   * // Get one Prestations
   * const prestations = await prisma.prestations.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PrestationsFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PrestationsFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrestationsClient<runtime.Types.Result.GetResult<Prisma.$PrestationsPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Prestations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrestationsFindFirstArgs} args - Arguments to find a Prestations
   * @example
   * // Get one Prestations
   * const prestations = await prisma.prestations.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PrestationsFindFirstArgs>(args?: Prisma.SelectSubset<T, PrestationsFindFirstArgs<ExtArgs>>): Prisma.Prisma__PrestationsClient<runtime.Types.Result.GetResult<Prisma.$PrestationsPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Prestations that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrestationsFindFirstOrThrowArgs} args - Arguments to find a Prestations
   * @example
   * // Get one Prestations
   * const prestations = await prisma.prestations.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PrestationsFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PrestationsFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PrestationsClient<runtime.Types.Result.GetResult<Prisma.$PrestationsPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Prestations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrestationsFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Prestations
   * const prestations = await prisma.prestations.findMany()
   * 
   * // Get first 10 Prestations
   * const prestations = await prisma.prestations.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const prestationsWithIdOnly = await prisma.prestations.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PrestationsFindManyArgs>(args?: Prisma.SelectSubset<T, PrestationsFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrestationsPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Prestations.
   * @param {PrestationsCreateArgs} args - Arguments to create a Prestations.
   * @example
   * // Create one Prestations
   * const Prestations = await prisma.prestations.create({
   *   data: {
   *     // ... data to create a Prestations
   *   }
   * })
   * 
   */
  create<T extends PrestationsCreateArgs>(args: Prisma.SelectSubset<T, PrestationsCreateArgs<ExtArgs>>): Prisma.Prisma__PrestationsClient<runtime.Types.Result.GetResult<Prisma.$PrestationsPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Prestations.
   * @param {PrestationsCreateManyArgs} args - Arguments to create many Prestations.
   * @example
   * // Create many Prestations
   * const prestations = await prisma.prestations.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PrestationsCreateManyArgs>(args?: Prisma.SelectSubset<T, PrestationsCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Prestations and returns the data saved in the database.
   * @param {PrestationsCreateManyAndReturnArgs} args - Arguments to create many Prestations.
   * @example
   * // Create many Prestations
   * const prestations = await prisma.prestations.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Prestations and only return the `id`
   * const prestationsWithIdOnly = await prisma.prestations.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PrestationsCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PrestationsCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrestationsPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Prestations.
   * @param {PrestationsDeleteArgs} args - Arguments to delete one Prestations.
   * @example
   * // Delete one Prestations
   * const Prestations = await prisma.prestations.delete({
   *   where: {
   *     // ... filter to delete one Prestations
   *   }
   * })
   * 
   */
  delete<T extends PrestationsDeleteArgs>(args: Prisma.SelectSubset<T, PrestationsDeleteArgs<ExtArgs>>): Prisma.Prisma__PrestationsClient<runtime.Types.Result.GetResult<Prisma.$PrestationsPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Prestations.
   * @param {PrestationsUpdateArgs} args - Arguments to update one Prestations.
   * @example
   * // Update one Prestations
   * const prestations = await prisma.prestations.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PrestationsUpdateArgs>(args: Prisma.SelectSubset<T, PrestationsUpdateArgs<ExtArgs>>): Prisma.Prisma__PrestationsClient<runtime.Types.Result.GetResult<Prisma.$PrestationsPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Prestations.
   * @param {PrestationsDeleteManyArgs} args - Arguments to filter Prestations to delete.
   * @example
   * // Delete a few Prestations
   * const { count } = await prisma.prestations.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PrestationsDeleteManyArgs>(args?: Prisma.SelectSubset<T, PrestationsDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Prestations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrestationsUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Prestations
   * const prestations = await prisma.prestations.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PrestationsUpdateManyArgs>(args: Prisma.SelectSubset<T, PrestationsUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Prestations and returns the data updated in the database.
   * @param {PrestationsUpdateManyAndReturnArgs} args - Arguments to update many Prestations.
   * @example
   * // Update many Prestations
   * const prestations = await prisma.prestations.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Prestations and only return the `id`
   * const prestationsWithIdOnly = await prisma.prestations.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PrestationsUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PrestationsUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PrestationsPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Prestations.
   * @param {PrestationsUpsertArgs} args - Arguments to update or create a Prestations.
   * @example
   * // Update or create a Prestations
   * const prestations = await prisma.prestations.upsert({
   *   create: {
   *     // ... data to create a Prestations
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Prestations we want to update
   *   }
   * })
   */
  upsert<T extends PrestationsUpsertArgs>(args: Prisma.SelectSubset<T, PrestationsUpsertArgs<ExtArgs>>): Prisma.Prisma__PrestationsClient<runtime.Types.Result.GetResult<Prisma.$PrestationsPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Prestations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrestationsCountArgs} args - Arguments to filter Prestations to count.
   * @example
   * // Count the number of Prestations
   * const count = await prisma.prestations.count({
   *   where: {
   *     // ... the filter for the Prestations we want to count
   *   }
   * })
  **/
  count<T extends PrestationsCountArgs>(
    args?: Prisma.Subset<T, PrestationsCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PrestationsCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Prestations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrestationsAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PrestationsAggregateArgs>(args: Prisma.Subset<T, PrestationsAggregateArgs>): Prisma.PrismaPromise<GetPrestationsAggregateType<T>>

  /**
   * Group by Prestations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PrestationsGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PrestationsGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PrestationsGroupByArgs['orderBy'] }
      : { orderBy?: PrestationsGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PrestationsGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPrestationsGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Prestations model
 */
readonly fields: PrestationsFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Prestations.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PrestationsClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Prestations model
 */
export interface PrestationsFieldRefs {
  readonly id: Prisma.FieldRef<"Prestations", 'String'>
  readonly name: Prisma.FieldRef<"Prestations", 'String'>
  readonly price: Prisma.FieldRef<"Prestations", 'Int'>
  readonly isActive: Prisma.FieldRef<"Prestations", 'Boolean'>
  readonly createdAt: Prisma.FieldRef<"Prestations", 'DateTime'>
  readonly updatedAt: Prisma.FieldRef<"Prestations", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Prestations findUnique
 */
export type PrestationsFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
  /**
   * Filter, which Prestations to fetch.
   */
  where: Prisma.PrestationsWhereUniqueInput
}

/**
 * Prestations findUniqueOrThrow
 */
export type PrestationsFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
  /**
   * Filter, which Prestations to fetch.
   */
  where: Prisma.PrestationsWhereUniqueInput
}

/**
 * Prestations findFirst
 */
export type PrestationsFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
  /**
   * Filter, which Prestations to fetch.
   */
  where?: Prisma.PrestationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Prestations to fetch.
   */
  orderBy?: Prisma.PrestationsOrderByWithRelationInput | Prisma.PrestationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Prestations.
   */
  cursor?: Prisma.PrestationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Prestations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Prestations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Prestations.
   */
  distinct?: Prisma.PrestationsScalarFieldEnum | Prisma.PrestationsScalarFieldEnum[]
}

/**
 * Prestations findFirstOrThrow
 */
export type PrestationsFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
  /**
   * Filter, which Prestations to fetch.
   */
  where?: Prisma.PrestationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Prestations to fetch.
   */
  orderBy?: Prisma.PrestationsOrderByWithRelationInput | Prisma.PrestationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Prestations.
   */
  cursor?: Prisma.PrestationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Prestations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Prestations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Prestations.
   */
  distinct?: Prisma.PrestationsScalarFieldEnum | Prisma.PrestationsScalarFieldEnum[]
}

/**
 * Prestations findMany
 */
export type PrestationsFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
  /**
   * Filter, which Prestations to fetch.
   */
  where?: Prisma.PrestationsWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Prestations to fetch.
   */
  orderBy?: Prisma.PrestationsOrderByWithRelationInput | Prisma.PrestationsOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Prestations.
   */
  cursor?: Prisma.PrestationsWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Prestations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Prestations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Prestations.
   */
  distinct?: Prisma.PrestationsScalarFieldEnum | Prisma.PrestationsScalarFieldEnum[]
}

/**
 * Prestations create
 */
export type PrestationsCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
  /**
   * The data needed to create a Prestations.
   */
  data: Prisma.XOR<Prisma.PrestationsCreateInput, Prisma.PrestationsUncheckedCreateInput>
}

/**
 * Prestations createMany
 */
export type PrestationsCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Prestations.
   */
  data: Prisma.PrestationsCreateManyInput | Prisma.PrestationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Prestations createManyAndReturn
 */
export type PrestationsCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
  /**
   * The data used to create many Prestations.
   */
  data: Prisma.PrestationsCreateManyInput | Prisma.PrestationsCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Prestations update
 */
export type PrestationsUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
  /**
   * The data needed to update a Prestations.
   */
  data: Prisma.XOR<Prisma.PrestationsUpdateInput, Prisma.PrestationsUncheckedUpdateInput>
  /**
   * Choose, which Prestations to update.
   */
  where: Prisma.PrestationsWhereUniqueInput
}

/**
 * Prestations updateMany
 */
export type PrestationsUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Prestations.
   */
  data: Prisma.XOR<Prisma.PrestationsUpdateManyMutationInput, Prisma.PrestationsUncheckedUpdateManyInput>
  /**
   * Filter which Prestations to update
   */
  where?: Prisma.PrestationsWhereInput
  /**
   * Limit how many Prestations to update.
   */
  limit?: number
}

/**
 * Prestations updateManyAndReturn
 */
export type PrestationsUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
  /**
   * The data used to update Prestations.
   */
  data: Prisma.XOR<Prisma.PrestationsUpdateManyMutationInput, Prisma.PrestationsUncheckedUpdateManyInput>
  /**
   * Filter which Prestations to update
   */
  where?: Prisma.PrestationsWhereInput
  /**
   * Limit how many Prestations to update.
   */
  limit?: number
}

/**
 * Prestations upsert
 */
export type PrestationsUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
  /**
   * The filter to search for the Prestations to update in case it exists.
   */
  where: Prisma.PrestationsWhereUniqueInput
  /**
   * In case the Prestations found by the `where` argument doesn't exist, create a new Prestations with this data.
   */
  create: Prisma.XOR<Prisma.PrestationsCreateInput, Prisma.PrestationsUncheckedCreateInput>
  /**
   * In case the Prestations was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PrestationsUpdateInput, Prisma.PrestationsUncheckedUpdateInput>
}

/**
 * Prestations delete
 */
export type PrestationsDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
  /**
   * Filter which Prestations to delete.
   */
  where: Prisma.PrestationsWhereUniqueInput
}

/**
 * Prestations deleteMany
 */
export type PrestationsDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Prestations to delete
   */
  where?: Prisma.PrestationsWhereInput
  /**
   * Limit how many Prestations to delete.
   */
  limit?: number
}

/**
 * Prestations without action
 */
export type PrestationsDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Prestations
   */
  select?: Prisma.PrestationsSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Prestations
   */
  omit?: Prisma.PrestationsOmit<ExtArgs> | null
}
